/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as __tests___factories from "../__tests__/factories.js";
import type * as _utils_batchLoader from "../_utils/batchLoader.js";
import type * as _utils_errors from "../_utils/errors.js";
import type * as accountDeletionEmail from "../accountDeletionEmail.js";
import type * as agent_agentPipeline from "../agent/agentPipeline.js";
import type * as agent_coalescing from "../agent/coalescing.js";
import type * as agent_knowledgeBackfill from "../agent/knowledgeBackfill.js";
import type * as agent_outcomeFeedback from "../agent/outcomeFeedback.js";
import type * as agent_referenceMonitor from "../agent/referenceMonitor.js";
import type * as agent_shadowScorecard from "../agent/shadowScorecard.js";
import type * as agent_shadowSimilarity from "../agent/shadowSimilarity.js";
import type * as agent_shared_draftService from "../agent/shared/draftService.js";
import type * as agent_steps_clarify_attachment from "../agent/steps/clarify/attachment.js";
import type * as agent_steps_clarify_index from "../agent/steps/clarify/index.js";
import type * as agent_steps_classify_index from "../agent/steps/classify/index.js";
import type * as agent_steps_context_retrieval_currentMessage from "../agent/steps/context_retrieval/currentMessage.js";
import type * as agent_steps_context_retrieval_emergency from "../agent/steps/context_retrieval/emergency.js";
import type * as agent_steps_context_retrieval_index from "../agent/steps/context_retrieval/index.js";
import type * as agent_steps_context_retrieval_quarantine from "../agent/steps/context_retrieval/quarantine.js";
import type * as agent_steps_draft_attachment from "../agent/steps/draft/attachment.js";
import type * as agent_steps_draft_index from "../agent/steps/draft/index.js";
import type * as agent_steps_draft_recall from "../agent/steps/draft/recall.js";
import type * as agent_steps_draft_sanitize from "../agent/steps/draft/sanitize.js";
import type * as agent_steps_index from "../agent/steps/index.js";
import type * as agent_steps_route_index from "../agent/steps/route/index.js";
import type * as agent_steps_security_scan_index from "../agent/steps/security_scan/index.js";
import type * as agent_steps_security_scan_patterns from "../agent/steps/security_scan/patterns.js";
import type * as agent_steps_types from "../agent/steps/types.js";
import type * as agent_walker from "../agent/walker.js";
import type * as agentConfigMutations from "../agentConfigMutations.js";
import type * as agentHealth from "../agentHealth.js";
import type * as analytics_adaptiveDashboard from "../analytics/adaptiveDashboard.js";
import type * as analytics_dashboard from "../analytics/dashboard.js";
import type * as analytics_evalHarness from "../analytics/evalHarness.js";
import type * as analytics_llmUsage from "../analytics/llmUsage.js";
import type * as analytics_qualityMetrics from "../analytics/qualityMetrics.js";
import type * as analytics_reporter from "../analytics/reporter.js";
import type * as analytics_reputationQueries from "../analytics/reputationQueries.js";
import type * as analytics_sendingReputation from "../analytics/sendingReputation.js";
import type * as analytics_spendBudget from "../analytics/spendBudget.js";
import type * as assistant_conversations from "../assistant/conversations.js";
import type * as assistant_insights from "../assistant/insights.js";
import type * as assistant_prompt from "../assistant/prompt.js";
import type * as assistant_runner from "../assistant/runner.js";
import type * as assistant_tools from "../assistant/tools.js";
import type * as auditActions_catalog from "../auditActions/catalog.js";
import type * as auditLogs from "../auditLogs.js";
import type * as auth_accountDeletion from "../auth/accountDeletion.js";
import type * as auth_accountManagement from "../auth/accountManagement.js";
import type * as auth_apiAuth from "../auth/apiAuth.js";
import type * as auth_apiKeys from "../auth/apiKeys.js";
import type * as auth_apiScopes from "../auth/apiScopes.js";
import type * as auth_auth from "../auth/auth.js";
import type * as auth_config from "../auth/config.js";
import type * as auth_memberErasure from "../auth/memberErasure.js";
import type * as auth_membership from "../auth/membership.js";
import type * as auth_onboarding from "../auth/onboarding.js";
import type * as auth_userOnboarding from "../auth/userOnboarding.js";
import type * as auth_userProfiles from "../auth/userProfiles.js";
import type * as automations_analytics from "../automations/analytics.js";
import type * as automations_automations from "../automations/automations.js";
import type * as automations_guards from "../automations/guards.js";
import type * as automations_lifecycle from "../automations/lifecycle.js";
import type * as automations_listing from "../automations/listing.js";
import type * as automations_statShards from "../automations/statShards.js";
import type * as automations_stepExecutorQueries from "../automations/stepExecutorQueries.js";
import type * as automations_stepWalker from "../automations/stepWalker.js";
import type * as automations_steps from "../automations/steps.js";
import type * as automations_steps_condition_index from "../automations/steps/condition/index.js";
import type * as automations_steps_condition_queries from "../automations/steps/condition/queries.js";
import type * as automations_steps_delay_index from "../automations/steps/delay/index.js";
import type * as automations_steps_email_index from "../automations/steps/email/index.js";
import type * as automations_triggers from "../automations/triggers.js";
import type * as automations_triggers_contact_created_index from "../automations/triggers/contact_created/index.js";
import type * as automations_triggers_contact_updated_index from "../automations/triggers/contact_updated/index.js";
import type * as automations_triggers_event_received_index from "../automations/triggers/event_received/index.js";
import type * as automations_triggers_topic_subscribed_index from "../automations/triggers/topic_subscribed/index.js";
import type * as automations_triggers_types from "../automations/triggers/types.js";
import type * as automations_types from "../automations/types.js";
import type * as autonomy from "../autonomy.js";
import type * as autonomyFeedback from "../autonomyFeedback.js";
import type * as autonomyOutcome from "../autonomyOutcome.js";
import type * as autonomySuggestions from "../autonomySuggestions.js";
import type * as blockedEmails from "../blockedEmails.js";
import type * as campaigns_abTest from "../campaigns/abTest.js";
import type * as campaigns_abTestLifecycle from "../campaigns/abTestLifecycle.js";
import type * as campaigns_analytics from "../campaigns/analytics.js";
import type * as campaigns_archiveHttp from "../campaigns/archiveHttp.js";
import type * as campaigns_archiveQueries from "../campaigns/archiveQueries.js";
import type * as campaigns_audience from "../campaigns/audience.js";
import type * as campaigns_audienceResolution from "../campaigns/audienceResolution.js";
import type * as campaigns_campaigns from "../campaigns/campaigns.js";
import type * as campaigns_guards from "../campaigns/guards.js";
import type * as campaigns_lifecycle from "../campaigns/lifecycle.js";
import type * as campaigns_listing from "../campaigns/listing.js";
import type * as campaigns_organization from "../campaigns/organization.js";
import type * as campaigns_preflight from "../campaigns/preflight.js";
import type * as campaigns_scheduling from "../campaigns/scheduling.js";
import type * as campaigns_send from "../campaigns/send.js";
import type * as campaigns_sendJob from "../campaigns/sendJob.js";
import type * as campaigns_sendQueries from "../campaigns/sendQueries.js";
import type * as campaigns_sendVariantSplit from "../campaigns/sendVariantSplit.js";
import type * as campaigns_statShards from "../campaigns/statShards.js";
import type * as campaigns_testSend from "../campaigns/testSend.js";
import type * as channels_outbound from "../channels/outbound.js";
import type * as chat__helpers from "../chat/_helpers.js";
import type * as chat_attachments from "../chat/attachments.js";
import type * as chat_cleanup from "../chat/cleanup.js";
import type * as chat_dms from "../chat/dms.js";
import type * as chat_emailLink from "../chat/emailLink.js";
import type * as chat_members from "../chat/members.js";
import type * as chat_mentions from "../chat/mentions.js";
import type * as chat_messages from "../chat/messages.js";
import type * as chat_rooms from "../chat/rooms.js";
import type * as codeWorkTasks from "../codeWorkTasks.js";
import type * as conditions_contact_property_index from "../conditions/contact_property/index.js";
import type * as conditions_email_activity_index from "../conditions/email_activity/index.js";
import type * as conditions_index from "../conditions/index.js";
import type * as conditions_segmentMatch from "../conditions/segmentMatch.js";
import type * as conditions_topic_membership_index from "../conditions/topic_membership/index.js";
import type * as conditions_types from "../conditions/types.js";
import type * as confirmationEmail from "../confirmationEmail.js";
import type * as confirmationEmailQueries from "../confirmationEmailQueries.js";
import type * as contactActivities_catalog from "../contactActivities/catalog.js";
import type * as contactActivities_created_index from "../contactActivities/created/index.js";
import type * as contactActivities_doi_attested_index from "../contactActivities/doi_attested/index.js";
import type * as contactActivities_email_bounced_index from "../contactActivities/email_bounced/index.js";
import type * as contactActivities_email_clicked_index from "../contactActivities/email_clicked/index.js";
import type * as contactActivities_email_complained_index from "../contactActivities/email_complained/index.js";
import type * as contactActivities_email_opened_index from "../contactActivities/email_opened/index.js";
import type * as contactActivities_email_sent_index from "../contactActivities/email_sent/index.js";
import type * as contactActivities_inbound_received_index from "../contactActivities/inbound_received/index.js";
import type * as contactActivities_inbound_replied_index from "../contactActivities/inbound_replied/index.js";
import type * as contactActivities_property_updated_index from "../contactActivities/property_updated/index.js";
import type * as contactActivities_topic_confirmed_index from "../contactActivities/topic_confirmed/index.js";
import type * as contactActivities_topic_subscribed_index from "../contactActivities/topic_subscribed/index.js";
import type * as contactActivities_topic_unsubscribed_index from "../contactActivities/topic_unsubscribed/index.js";
import type * as contactActivities_types from "../contactActivities/types.js";
import type * as contactActivities_writer from "../contactActivities/writer.js";
import type * as contacts_activities from "../contacts/activities.js";
import type * as contacts_analytics from "../contacts/analytics.js";
import type * as contacts_api from "../contacts/api.js";
import type * as contacts_contacts from "../contacts/contacts.js";
import type * as contacts_creation from "../contacts/creation.js";
import type * as contacts_dataExport from "../contacts/dataExport.js";
import type * as contacts_doiLifecycle from "../contacts/doiLifecycle.js";
import type * as contacts_identities from "../contacts/identities.js";
import type * as contacts_import from "../contacts/import.js";
import type * as contacts_listing from "../contacts/listing.js";
import type * as contacts_organization from "../contacts/organization.js";
import type * as contacts_properties from "../contacts/properties.js";
import type * as contacts_propertyValues from "../contacts/propertyValues.js";
import type * as contacts_relationships from "../contacts/relationships.js";
import type * as contacts_resolution from "../contacts/resolution.js";
import type * as contacts_timeline from "../contacts/timeline.js";
import type * as crons from "../crons.js";
import type * as delivery_contactToken from "../delivery/contactToken.js";
import type * as delivery_enqueue from "../delivery/enqueue.js";
import type * as delivery_health from "../delivery/health.js";
import type * as delivery_messageIdRouting from "../delivery/messageIdRouting.js";
import type * as delivery_preferences from "../delivery/preferences.js";
import type * as delivery_preferencesHttp from "../delivery/preferencesHttp.js";
import type * as delivery_preferencesQueries from "../delivery/preferencesQueries.js";
import type * as delivery_sendCompletion from "../delivery/sendCompletion.js";
import type * as delivery_sendComposition_archive_snapshot_index from "../delivery/sendComposition/archive_snapshot/index.js";
import type * as delivery_sendComposition_automation_index from "../delivery/sendComposition/automation/index.js";
import type * as delivery_sendComposition_campaign_index from "../delivery/sendComposition/campaign/index.js";
import type * as delivery_sendComposition_feedbackId from "../delivery/sendComposition/feedbackId.js";
import type * as delivery_sendComposition_index from "../delivery/sendComposition/index.js";
import type * as delivery_sendComposition_listId from "../delivery/sendComposition/listId.js";
import type * as delivery_sendComposition_personalization from "../delivery/sendComposition/personalization.js";
import type * as delivery_sendComposition_plainText from "../delivery/sendComposition/plainText.js";
import type * as delivery_sendComposition_test_index from "../delivery/sendComposition/test/index.js";
import type * as delivery_sendComposition_trackingUrl from "../delivery/sendComposition/trackingUrl.js";
import type * as delivery_sendComposition_transactional_index from "../delivery/sendComposition/transactional/index.js";
import type * as delivery_sendComposition_transform from "../delivery/sendComposition/transform.js";
import type * as delivery_sendComposition_types from "../delivery/sendComposition/types.js";
import type * as delivery_sendLifecycle from "../delivery/sendLifecycle.js";
import type * as delivery_sendLifecycle_effects from "../delivery/sendLifecycle/effects.js";
import type * as delivery_sendLifecycle_feedbackReducers from "../delivery/sendLifecycle/feedbackReducers.js";
import type * as delivery_sendLifecycle_lookups from "../delivery/sendLifecycle/lookups.js";
import type * as delivery_sendLifecycle_reducers from "../delivery/sendLifecycle/reducers.js";
import type * as delivery_sendLifecycle_types from "../delivery/sendLifecycle/types.js";
import type * as delivery_sends from "../delivery/sends.js";
import type * as delivery_status from "../delivery/status.js";
import type * as delivery_suppressionMirror from "../delivery/suppressionMirror.js";
import type * as delivery_tokenValidation from "../delivery/tokenValidation.js";
import type * as delivery_tracking from "../delivery/tracking.js";
import type * as delivery_trackingHttp from "../delivery/trackingHttp.js";
import type * as delivery_unsubscribe from "../delivery/unsubscribe.js";
import type * as delivery_unsubscribeHttp from "../delivery/unsubscribeHttp.js";
import type * as delivery_unsubscribeQueries from "../delivery/unsubscribeQueries.js";
import type * as delivery_warmingSync from "../delivery/warmingSync.js";
import type * as delivery_worker from "../delivery/worker.js";
import type * as delivery_workpool from "../delivery/workpool.js";
import type * as devShortcuts__guard from "../devShortcuts/_guard.js";
import type * as devShortcuts_forceVerifyDomain from "../devShortcuts/forceVerifyDomain.js";
import type * as devShortcuts_reset from "../devShortcuts/reset.js";
import type * as domains_dmarc from "../domains/dmarc.js";
import type * as domains_dnsMatch from "../domains/dnsMatch.js";
import type * as domains_dnsVerification from "../domains/dnsVerification.js";
import type * as domains_domains from "../domains/domains.js";
import type * as domains_lifecycle from "../domains/lifecycle.js";
import type * as domains_providers_index from "../domains/providers/index.js";
import type * as domains_providers_mta_index from "../domains/providers/mta/index.js";
import type * as domains_providers_registerAction from "../domains/providers/registerAction.js";
import type * as domains_providers_ses_index from "../domains/providers/ses/index.js";
import type * as domains_providers_types from "../domains/providers/types.js";
import type * as domains_queries from "../domains/queries.js";
import type * as domains_reverseDns from "../domains/reverseDns.js";
import type * as domains_spf from "../domains/spf.js";
import type * as domains_tlsRpt from "../domains/tlsRpt.js";
import type * as domains_trackingDomains from "../domains/trackingDomains.js";
import type * as emailBlocks_blocks from "../emailBlocks/blocks.js";
import type * as emailBlocks_module from "../emailBlocks/module.js";
import type * as emailBlocks_rendering from "../emailBlocks/rendering.js";
import type * as emailBlocks_renderingPool from "../emailBlocks/renderingPool.js";
import type * as emailTemplates_emails from "../emailTemplates/emails.js";
import type * as emailTemplates_i18n from "../emailTemplates/i18n.js";
import type * as emailTemplates_lifecycle from "../emailTemplates/lifecycle.js";
import type * as emailTemplates_listing from "../emailTemplates/listing.js";
import type * as emailTemplates_organization from "../emailTemplates/organization.js";
import type * as emailTemplates_translationMerge from "../emailTemplates/translationMerge.js";
import type * as eventsApi from "../eventsApi.js";
import type * as forms_apiHttp from "../forms/apiHttp.js";
import type * as forms_endpoints from "../forms/endpoints.js";
import type * as forms_submission from "../forms/submission.js";
import type * as globalSearch from "../globalSearch.js";
import type * as http from "../http.js";
import type * as inbox_askEagerness from "../inbox/askEagerness.js";
import type * as inbox_askEagernessSettings from "../inbox/askEagernessSettings.js";
import type * as inbox_attachmentMatch from "../inbox/attachmentMatch.js";
import type * as inbox_attachmentSuggest from "../inbox/attachmentSuggest.js";
import type * as inbox_attachmentValidators from "../inbox/attachmentValidators.js";
import type * as inbox_clarification from "../inbox/clarification.js";
import type * as inbox_clarificationLog from "../inbox/clarificationLog.js";
import type * as inbox_clarificationMemory from "../inbox/clarificationMemory.js";
import type * as inbox_clarificationMemoryMatch from "../inbox/clarificationMemoryMatch.js";
import type * as inbox_clarificationSlots from "../inbox/clarificationSlots.js";
import type * as inbox_clarificationValidators from "../inbox/clarificationValidators.js";
import type * as inbox_messages from "../inbox/messages.js";
import type * as inbox_mutations from "../inbox/mutations.js";
import type * as inbox_presence from "../inbox/presence.js";
import type * as inbox_processingLifecycle from "../inbox/processingLifecycle.js";
import type * as inbox_processingLifecycle_autoSendCancel from "../inbox/processingLifecycle/autoSendCancel.js";
import type * as inbox_processingLifecycle_effects from "../inbox/processingLifecycle/effects.js";
import type * as inbox_processingLifecycle_reducers from "../inbox/processingLifecycle/reducers.js";
import type * as inbox_processingLifecycle_types from "../inbox/processingLifecycle/types.js";
import type * as inbox_queries from "../inbox/queries.js";
import type * as inbox_reads from "../inbox/reads.js";
import type * as inbox_snooze from "../inbox/snooze.js";
import type * as inbox_stepOutputs from "../inbox/stepOutputs.js";
import type * as inbox_threadSort from "../inbox/threadSort.js";
import type * as inbox_threads_module from "../inbox/threads/module.js";
import type * as integrationImports__common from "../integrationImports/_common.js";
import type * as integrationImports_providers_index from "../integrationImports/providers/index.js";
import type * as integrationImports_providers_mailchimp_index from "../integrationImports/providers/mailchimp/index.js";
import type * as integrationImports_providers_stripe_index from "../integrationImports/providers/stripe/index.js";
import type * as integrationImports_walker from "../integrationImports/walker.js";
import type * as knowledge_edgeBackfill from "../knowledge/edgeBackfill.js";
import type * as knowledge_edgeInference from "../knowledge/edgeInference.js";
import type * as knowledge_edges from "../knowledge/edges.js";
import type * as knowledge_extraction from "../knowledge/extraction.js";
import type * as knowledge_graph from "../knowledge/graph.js";
import type * as knowledge_graphAnalytics from "../knowledge/graphAnalytics.js";
import type * as knowledge_graphAnalyticsRecompute from "../knowledge/graphAnalyticsRecompute.js";
import type * as knowledge_graphTraversal from "../knowledge/graphTraversal.js";
import type * as knowledge_maintenance from "../knowledge/maintenance.js";
import type * as knowledge_relationDecay from "../knowledge/relationDecay.js";
import type * as knowledge_retrieval from "../knowledge/retrieval.js";
import type * as lib_auditLog from "../lib/auditLog.js";
import type * as lib_authedFunctions from "../lib/authedFunctions.js";
import type * as lib_automationConfigTypes from "../lib/automationConfigTypes.js";
import type * as lib_autonomyRules from "../lib/autonomyRules.js";
import type * as lib_constants from "../lib/constants.js";
import type * as lib_contactCountHelpers from "../lib/contactCountHelpers.js";
import type * as lib_contactHelpers from "../lib/contactHelpers.js";
import type * as lib_contactJunctions from "../lib/contactJunctions.js";
import type * as lib_contactMutations from "../lib/contactMutations.js";
import type * as lib_contactScope from "../lib/contactScope.js";
import type * as lib_convexValidators from "../lib/convexValidators.js";
import type * as lib_cors from "../lib/cors.js";
import type * as lib_credentialCrypto from "../lib/credentialCrypto.js";
import type * as lib_emailAddress from "../lib/emailAddress.js";
import type * as lib_emailHelpers from "../lib/emailHelpers.js";
import type * as lib_emailProviders_domainVerification from "../lib/emailProviders/domainVerification.js";
import type * as lib_emailProviders_mtaIdentity from "../lib/emailProviders/mtaIdentity.js";
import type * as lib_emailProviders_sesIdentity from "../lib/emailProviders/sesIdentity.js";
import type * as lib_emailTranslations from "../lib/emailTranslations.js";
import type * as lib_env from "../lib/env.js";
import type * as lib_featureFlags from "../lib/featureFlags.js";
import type * as lib_graphAnalyticsCompute from "../lib/graphAnalyticsCompute.js";
import type * as lib_graphRank from "../lib/graphRank.js";
import type * as lib_httpResponse from "../lib/httpResponse.js";
import type * as lib_inboundClassification from "../lib/inboundClassification.js";
import type * as lib_inboxStats from "../lib/inboxStats.js";
import type * as lib_inputGuards from "../lib/inputGuards.js";
import type * as lib_ipBlocklist from "../lib/ipBlocklist.js";
import type * as lib_knowledgeDedup from "../lib/knowledgeDedup.js";
import type * as lib_knowledgeEdges from "../lib/knowledgeEdges.js";
import type * as lib_knowledgePrecedence from "../lib/knowledgePrecedence.js";
import type * as lib_listing from "../lib/listing.js";
import type * as lib_llm_complexity from "../lib/llm/complexity.js";
import type * as lib_llm_dispatch from "../lib/llm/dispatch.js";
import type * as lib_llm_pricing from "../lib/llm/pricing.js";
import type * as lib_llm_promptCache from "../lib/llm/promptCache.js";
import type * as lib_llmProvider from "../lib/llmProvider.js";
import type * as lib_mailHost from "../lib/mailHost.js";
import type * as lib_mailSnooze from "../lib/mailSnooze.js";
import type * as lib_pagination from "../lib/pagination.js";
import type * as lib_paginationCursor from "../lib/paginationCursor.js";
import type * as lib_posthog from "../lib/posthog.js";
import type * as lib_posthogHelpers from "../lib/posthogHelpers.js";
import type * as lib_publicTokenEndpoint from "../lib/publicTokenEndpoint.js";
import type * as lib_queryHelpers from "../lib/queryHelpers.js";
import type * as lib_randomToken from "../lib/randomToken.js";
import type * as lib_receivedAtCursor from "../lib/receivedAtCursor.js";
import type * as lib_rrf from "../lib/rrf.js";
import type * as lib_runtimeLog from "../lib/runtimeLog.js";
import type * as lib_safeCompare from "../lib/safeCompare.js";
import type * as lib_scannerHealth from "../lib/scannerHealth.js";
import type * as lib_secretLeakScan from "../lib/secretLeakScan.js";
import type * as lib_sendDailyStats from "../lib/sendDailyStats.js";
import type * as lib_sendProviders_capability from "../lib/sendProviders/capability.js";
import type * as lib_sendProviders_dispatch from "../lib/sendProviders/dispatch.js";
import type * as lib_sendProviders_health from "../lib/sendProviders/health.js";
import type * as lib_sendProviders_index from "../lib/sendProviders/index.js";
import type * as lib_sendProviders_mta_index from "../lib/sendProviders/mta/index.js";
import type * as lib_sendProviders_resend_index from "../lib/sendProviders/resend/index.js";
import type * as lib_sendProviders_route from "../lib/sendProviders/route.js";
import type * as lib_sendProviders_routing from "../lib/sendProviders/routing.js";
import type * as lib_sendProviders_ses_index from "../lib/sendProviders/ses/index.js";
import type * as lib_sendProviders_strategies_index from "../lib/sendProviders/strategies/index.js";
import type * as lib_sendProviders_strategies_priority_failover_index from "../lib/sendProviders/strategies/priority_failover/index.js";
import type * as lib_sendProviders_strategies_single_index from "../lib/sendProviders/strategies/single/index.js";
import type * as lib_sendProviders_strategies_types from "../lib/sendProviders/strategies/types.js";
import type * as lib_sendProviders_strategies_workload_split_index from "../lib/sendProviders/strategies/workload_split/index.js";
import type * as lib_sendProviders_types from "../lib/sendProviders/types.js";
import type * as lib_sendingLimits from "../lib/sendingLimits.js";
import type * as lib_sessionOrganization from "../lib/sessionOrganization.js";
import type * as lib_ssrfGuard from "../lib/ssrfGuard.js";
import type * as lib_statShards from "../lib/statShards.js";
import type * as lib_suppression from "../lib/suppression.js";
import type * as lib_systemEmails from "../lib/systemEmails.js";
import type * as lib_tenantTables from "../lib/tenantTables.js";
import type * as lib_textPreview from "../lib/textPreview.js";
import type * as lib_workingHours from "../lib/workingHours.js";
import type * as mail_ai from "../mail/ai.js";
import type * as mail_aiCoach from "../mail/aiCoach.js";
import type * as mail_aiGate from "../mail/aiGate.js";
import type * as mail_aiScheduling from "../mail/aiScheduling.js";
import type * as mail_aliases from "../mail/aliases.js";
import type * as mail_aliasesActions from "../mail/aliasesActions.js";
import type * as mail_appPasswords from "../mail/appPasswords.js";
import type * as mail_authHttp from "../mail/authHttp.js";
import type * as mail_authRateLimit from "../mail/authRateLimit.js";
import type * as mail_availability from "../mail/availability.js";
import type * as mail_brief from "../mail/brief.js";
import type * as mail_category from "../mail/category.js";
import type * as mail_categoryClassify from "../mail/categoryClassify.js";
import type * as mail_commitmentExtract from "../mail/commitmentExtract.js";
import type * as mail_commitments from "../mail/commitments.js";
import type * as mail_contacts from "../mail/contacts.js";
import type * as mail_dailyBrief from "../mail/dailyBrief.js";
import type * as mail_delivery from "../mail/delivery.js";
import type * as mail_deliveryHooks from "../mail/deliveryHooks.js";
import type * as mail_draftLifecycle from "../mail/draftLifecycle.js";
import type * as mail_draftOnArrival from "../mail/draftOnArrival.js";
import type * as mail_draftOnArrivalStore from "../mail/draftOnArrivalStore.js";
import type * as mail_draftStreamStore from "../mail/draftStreamStore.js";
import type * as mail_drafts from "../mail/drafts.js";
import type * as mail_editLearning from "../mail/editLearning.js";
import type * as mail_editLearningValidators from "../mail/editLearningValidators.js";
import type * as mail_externalAccounts from "../mail/externalAccounts.js";
import type * as mail_externalAccountsActions from "../mail/externalAccountsActions.js";
import type * as mail_externalDelivery from "../mail/externalDelivery.js";
import type * as mail_filters from "../mail/filters.js";
import type * as mail_folders from "../mail/folders.js";
import type * as mail_followUps from "../mail/followUps.js";
import type * as mail_forwarding from "../mail/forwarding.js";
import type * as mail_handlingRules from "../mail/handlingRules.js";
import type * as mail_handlingRules_engine from "../mail/handlingRules/engine.js";
import type * as mail_handlingRulesCompile from "../mail/handlingRulesCompile.js";
import type * as mail_identities from "../mail/identities.js";
import type * as mail_imap from "../mail/imap.js";
import type * as mail_labels from "../mail/labels.js";
import type * as mail_mailbox from "../mail/mailbox.js";
import type * as mail_mailboxActions from "../mail/mailboxActions.js";
import type * as mail_mailboxQueries from "../mail/mailboxQueries.js";
import type * as mail_messageActions from "../mail/messageActions.js";
import type * as mail_migration from "../mail/migration.js";
import type * as mail_migrationIndexing from "../mail/migrationIndexing.js";
import type * as mail_mtaClient from "../mail/mtaClient.js";
import type * as mail_needsReply from "../mail/needsReply.js";
import type * as mail_needsReplyClarify from "../mail/needsReplyClarify.js";
import type * as mail_needsReplyClassify from "../mail/needsReplyClassify.js";
import type * as mail_needsReplyScoring from "../mail/needsReplyScoring.js";
import type * as mail_outbound from "../mail/outbound.js";
import type * as mail_outboundCron from "../mail/outboundCron.js";
import type * as mail_outboundQueries from "../mail/outboundQueries.js";
import type * as mail_pendingMailbox from "../mail/pendingMailbox.js";
import type * as mail_permissions from "../mail/permissions.js";
import type * as mail_postboxOutboundLifecycle from "../mail/postboxOutboundLifecycle.js";
import type * as mail_priorityScore from "../mail/priorityScore.js";
import type * as mail_replyOptions from "../mail/replyOptions.js";
import type * as mail_reviseDraft from "../mail/reviseDraft.js";
import type * as mail_rfc822 from "../mail/rfc822.js";
import type * as mail_settings from "../mail/settings.js";
import type * as mail_signatures from "../mail/signatures.js";
import type * as mail_snippets from "../mail/snippets.js";
import type * as mail_snooze from "../mail/snooze.js";
import type * as mail_summaryCache from "../mail/summaryCache.js";
import type * as mail_unsubscribe from "../mail/unsubscribe.js";
import type * as mail_vacation from "../mail/vacation.js";
import type * as mail_voiceProfile from "../mail/voiceProfile.js";
import type * as mail_voiceProfileActions from "../mail/voiceProfileActions.js";
import type * as mail_voiceProfileText from "../mail/voiceProfileText.js";
import type * as mail_webhook from "../mail/webhook.js";
import type * as maintenance_retention from "../maintenance/retention.js";
import type * as mediaAssets from "../mediaAssets.js";
import type * as migrations_0005_channel_generic_rename from "../migrations/0005_channel_generic_rename.js";
import type * as migrations_0006_postbox_outbound_recipients from "../migrations/0006_postbox_outbound_recipients.js";
import type * as migrations_0018_sending_domain_identity_sibling from "../migrations/0018_sending_domain_identity_sibling.js";
import type * as migrations_0027_drain_inflight_integration_imports from "../migrations/0027_drain_inflight_integration_imports.js";
import type * as migrations_0032_thread_contact_identifier from "../migrations/0032_thread_contact_identifier.js";
import type * as migrations_0033_campaign_audience from "../migrations/0033_campaign_audience.js";
import type * as mtaWebhook from "../mtaWebhook.js";
import type * as organizations_abuseGate from "../organizations/abuseGate.js";
import type * as organizations_abuseStatus from "../organizations/abuseStatus.js";
import type * as organizations_deletion_steps__common from "../organizations/deletion/steps/_common.js";
import type * as organizations_deletion_steps_contacts from "../organizations/deletion/steps/contacts.js";
import type * as organizations_deletion_steps_domains from "../organizations/deletion/steps/domains.js";
import type * as organizations_deletion_steps_mailDrafts from "../organizations/deletion/steps/mailDrafts.js";
import type * as organizations_deletion_steps_mailMessages from "../organizations/deletion/steps/mailMessages.js";
import type * as organizations_deletion_steps_mediaAssets from "../organizations/deletion/steps/mediaAssets.js";
import type * as organizations_deletion_steps_semanticFiles from "../organizations/deletion/steps/semanticFiles.js";
import type * as organizations_deletion_steps_sweep from "../organizations/deletion/steps/sweep.js";
import type * as organizations_deletion_steps_transactionalSends from "../organizations/deletion/steps/transactionalSends.js";
import type * as organizations_deletion_walker from "../organizations/deletion/walker.js";
import type * as organizations_featureFlags from "../organizations/featureFlags.js";
import type * as organizations_settings from "../organizations/settings.js";
import type * as platformAdmin_mutations from "../platformAdmin/mutations.js";
import type * as platformAdmin_platformAdmin from "../platformAdmin/platformAdmin.js";
import type * as platformAdmin_queries from "../platformAdmin/queries.js";
import type * as providerRoutes from "../providerRoutes.js";
import type * as publicRateLimit from "../publicRateLimit.js";
import type * as quickQuery from "../quickQuery.js";
import type * as quickQueryGate from "../quickQueryGate.js";
import type * as rateLimiter from "../rateLimiter.js";
import type * as resendWebhook from "../resendWebhook.js";
import type * as schema_askEagerness from "../schema/askEagerness.js";
import type * as schema_assistant from "../schema/assistant.js";
import type * as schema_auth from "../schema/auth.js";
import type * as schema_automations from "../schema/automations.js";
import type * as schema_autonomy from "../schema/autonomy.js";
import type * as schema_campaigns from "../schema/campaigns.js";
import type * as schema_chat from "../schema/chat.js";
import type * as schema_codeWork from "../schema/codeWork.js";
import type * as schema_contacts from "../schema/contacts.js";
import type * as schema_dashboard from "../schema/dashboard.js";
import type * as schema_delivery from "../schema/delivery.js";
import type * as schema_domains from "../schema/domains.js";
import type * as schema_draftStream from "../schema/draftStream.js";
import type * as schema_forms from "../schema/forms.js";
import type * as schema_inbox from "../schema/inbox.js";
import type * as schema_integrations from "../schema/integrations.js";
import type * as schema_knowledge from "../schema/knowledge.js";
import type * as schema_mail from "../schema/mail.js";
import type * as schema_messaging from "../schema/messaging.js";
import type * as schema_templates from "../schema/templates.js";
import type * as schema_topics from "../schema/topics.js";
import type * as schema_webhooks from "../schema/webhooks.js";
import type * as seedAdmin from "../seedAdmin.js";
import type * as seedDemo_index from "../seedDemo/index.js";
import type * as seedDemo_loaders_accounts from "../seedDemo/loaders/accounts.js";
import type * as seedDemo_loaders_automations from "../seedDemo/loaders/automations.js";
import type * as seedDemo_loaders_campaigns from "../seedDemo/loaders/campaigns.js";
import type * as seedDemo_loaders_contactTopics from "../seedDemo/loaders/contactTopics.js";
import type * as seedDemo_loaders_contacts from "../seedDemo/loaders/contacts.js";
import type * as seedDemo_loaders_domains from "../seedDemo/loaders/domains.js";
import type * as seedDemo_loaders_emailTemplates from "../seedDemo/loaders/emailTemplates.js";
import type * as seedDemo_loaders_savedBlocks from "../seedDemo/loaders/savedBlocks.js";
import type * as seedDemo_loaders_topics from "../seedDemo/loaders/topics.js";
import type * as seedDemo_loaders_types from "../seedDemo/loaders/types.js";
import type * as seedDemo_loaders_webhooks from "../seedDemo/loaders/webhooks.js";
import type * as segments from "../segments.js";
import type * as segments_listing from "../segments/listing.js";
import type * as semanticFileProcessing from "../semanticFileProcessing.js";
import type * as semanticFiles from "../semanticFiles.js";
import type * as shareLinkHttp from "../shareLinkHttp.js";
import type * as shareLinkQueries from "../shareLinkQueries.js";
import type * as shareLinks from "../shareLinks.js";
import type * as storage from "../storage.js";
import type * as systemHealth from "../systemHealth.js";
import type * as systemMail from "../systemMail.js";
import type * as systemUpdates from "../systemUpdates.js";
import type * as topics_apiHttp from "../topics/apiHttp.js";
import type * as topics_bulk from "../topics/bulk.js";
import type * as topics_doiHttp from "../topics/doiHttp.js";
import type * as topics_listing from "../topics/listing.js";
import type * as topics_subscription from "../topics/subscription.js";
import type * as topics_topics from "../topics/topics.js";
import type * as transactional_api from "../transactional/api.js";
import type * as transactional_dispatch from "../transactional/dispatch.js";
import type * as transactional_emails from "../transactional/emails.js";
import type * as transactional_lifecycle from "../transactional/lifecycle.js";
import type * as transactional_sends from "../transactional/sends.js";
import type * as transactional_translations from "../transactional/translations.js";
import type * as translate from "../translate.js";
import type * as unifiedMessages from "../unifiedMessages.js";
import type * as visualizationAgent from "../visualizationAgent.js";
import type * as webhooks_adapters_generic from "../webhooks/adapters/generic.js";
import type * as webhooks_adapters_meta from "../webhooks/adapters/meta.js";
import type * as webhooks_adapters_mta from "../webhooks/adapters/mta.js";
import type * as webhooks_adapters_resend from "../webhooks/adapters/resend.js";
import type * as webhooks_adapters_twilio from "../webhooks/adapters/twilio.js";
import type * as webhooks_channels from "../webhooks/channels.js";
import type * as webhooks_cleanup from "../webhooks/cleanup.js";
import type * as webhooks_delivery from "../webhooks/delivery.js";
import type * as webhooks_deliveryQueries from "../webhooks/deliveryQueries.js";
import type * as webhooks_dispatcher from "../webhooks/dispatcher.js";
import type * as webhooks_endpoints from "../webhooks/endpoints.js";
import type * as webhooks_events from "../webhooks/events.js";
import type * as webhooks_events_contactCreated_index from "../webhooks/events/contactCreated/index.js";
import type * as webhooks_events_emailBounced_index from "../webhooks/events/emailBounced/index.js";
import type * as webhooks_events_emailClicked_index from "../webhooks/events/emailClicked/index.js";
import type * as webhooks_events_emailComplained_index from "../webhooks/events/emailComplained/index.js";
import type * as webhooks_events_emailDelivered_index from "../webhooks/events/emailDelivered/index.js";
import type * as webhooks_events_emailOpened_index from "../webhooks/events/emailOpened/index.js";
import type * as webhooks_events_emailSent_index from "../webhooks/events/emailSent/index.js";
import type * as webhooks_events_registry from "../webhooks/events/registry.js";
import type * as webhooks_events_test_index from "../webhooks/events/test/index.js";
import type * as webhooks_events_topicUnsubscribed_index from "../webhooks/events/topicUnsubscribed/index.js";
import type * as webhooks_fanout from "../webhooks/fanout.js";
import type * as webhooks_githubHttp from "../webhooks/githubHttp.js";
import type * as webhooks_payloads from "../webhooks/payloads.js";
import type * as webhooks_pipeline from "../webhooks/pipeline.js";
import type * as webhooks_scheduleFanout from "../webhooks/scheduleFanout.js";
import type * as webhooks_security from "../webhooks/security.js";
import type * as webhooks_types from "../webhooks/types.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "__tests__/factories": typeof __tests___factories;
  "_utils/batchLoader": typeof _utils_batchLoader;
  "_utils/errors": typeof _utils_errors;
  accountDeletionEmail: typeof accountDeletionEmail;
  "agent/agentPipeline": typeof agent_agentPipeline;
  "agent/coalescing": typeof agent_coalescing;
  "agent/knowledgeBackfill": typeof agent_knowledgeBackfill;
  "agent/outcomeFeedback": typeof agent_outcomeFeedback;
  "agent/referenceMonitor": typeof agent_referenceMonitor;
  "agent/shadowScorecard": typeof agent_shadowScorecard;
  "agent/shadowSimilarity": typeof agent_shadowSimilarity;
  "agent/shared/draftService": typeof agent_shared_draftService;
  "agent/steps/clarify/attachment": typeof agent_steps_clarify_attachment;
  "agent/steps/clarify/index": typeof agent_steps_clarify_index;
  "agent/steps/classify/index": typeof agent_steps_classify_index;
  "agent/steps/context_retrieval/currentMessage": typeof agent_steps_context_retrieval_currentMessage;
  "agent/steps/context_retrieval/emergency": typeof agent_steps_context_retrieval_emergency;
  "agent/steps/context_retrieval/index": typeof agent_steps_context_retrieval_index;
  "agent/steps/context_retrieval/quarantine": typeof agent_steps_context_retrieval_quarantine;
  "agent/steps/draft/attachment": typeof agent_steps_draft_attachment;
  "agent/steps/draft/index": typeof agent_steps_draft_index;
  "agent/steps/draft/recall": typeof agent_steps_draft_recall;
  "agent/steps/draft/sanitize": typeof agent_steps_draft_sanitize;
  "agent/steps/index": typeof agent_steps_index;
  "agent/steps/route/index": typeof agent_steps_route_index;
  "agent/steps/security_scan/index": typeof agent_steps_security_scan_index;
  "agent/steps/security_scan/patterns": typeof agent_steps_security_scan_patterns;
  "agent/steps/types": typeof agent_steps_types;
  "agent/walker": typeof agent_walker;
  agentConfigMutations: typeof agentConfigMutations;
  agentHealth: typeof agentHealth;
  "analytics/adaptiveDashboard": typeof analytics_adaptiveDashboard;
  "analytics/dashboard": typeof analytics_dashboard;
  "analytics/evalHarness": typeof analytics_evalHarness;
  "analytics/llmUsage": typeof analytics_llmUsage;
  "analytics/qualityMetrics": typeof analytics_qualityMetrics;
  "analytics/reporter": typeof analytics_reporter;
  "analytics/reputationQueries": typeof analytics_reputationQueries;
  "analytics/sendingReputation": typeof analytics_sendingReputation;
  "analytics/spendBudget": typeof analytics_spendBudget;
  "assistant/conversations": typeof assistant_conversations;
  "assistant/insights": typeof assistant_insights;
  "assistant/prompt": typeof assistant_prompt;
  "assistant/runner": typeof assistant_runner;
  "assistant/tools": typeof assistant_tools;
  "auditActions/catalog": typeof auditActions_catalog;
  auditLogs: typeof auditLogs;
  "auth/accountDeletion": typeof auth_accountDeletion;
  "auth/accountManagement": typeof auth_accountManagement;
  "auth/apiAuth": typeof auth_apiAuth;
  "auth/apiKeys": typeof auth_apiKeys;
  "auth/apiScopes": typeof auth_apiScopes;
  "auth/auth": typeof auth_auth;
  "auth/config": typeof auth_config;
  "auth/memberErasure": typeof auth_memberErasure;
  "auth/membership": typeof auth_membership;
  "auth/onboarding": typeof auth_onboarding;
  "auth/userOnboarding": typeof auth_userOnboarding;
  "auth/userProfiles": typeof auth_userProfiles;
  "automations/analytics": typeof automations_analytics;
  "automations/automations": typeof automations_automations;
  "automations/guards": typeof automations_guards;
  "automations/lifecycle": typeof automations_lifecycle;
  "automations/listing": typeof automations_listing;
  "automations/statShards": typeof automations_statShards;
  "automations/stepExecutorQueries": typeof automations_stepExecutorQueries;
  "automations/stepWalker": typeof automations_stepWalker;
  "automations/steps": typeof automations_steps;
  "automations/steps/condition/index": typeof automations_steps_condition_index;
  "automations/steps/condition/queries": typeof automations_steps_condition_queries;
  "automations/steps/delay/index": typeof automations_steps_delay_index;
  "automations/steps/email/index": typeof automations_steps_email_index;
  "automations/triggers": typeof automations_triggers;
  "automations/triggers/contact_created/index": typeof automations_triggers_contact_created_index;
  "automations/triggers/contact_updated/index": typeof automations_triggers_contact_updated_index;
  "automations/triggers/event_received/index": typeof automations_triggers_event_received_index;
  "automations/triggers/topic_subscribed/index": typeof automations_triggers_topic_subscribed_index;
  "automations/triggers/types": typeof automations_triggers_types;
  "automations/types": typeof automations_types;
  autonomy: typeof autonomy;
  autonomyFeedback: typeof autonomyFeedback;
  autonomyOutcome: typeof autonomyOutcome;
  autonomySuggestions: typeof autonomySuggestions;
  blockedEmails: typeof blockedEmails;
  "campaigns/abTest": typeof campaigns_abTest;
  "campaigns/abTestLifecycle": typeof campaigns_abTestLifecycle;
  "campaigns/analytics": typeof campaigns_analytics;
  "campaigns/archiveHttp": typeof campaigns_archiveHttp;
  "campaigns/archiveQueries": typeof campaigns_archiveQueries;
  "campaigns/audience": typeof campaigns_audience;
  "campaigns/audienceResolution": typeof campaigns_audienceResolution;
  "campaigns/campaigns": typeof campaigns_campaigns;
  "campaigns/guards": typeof campaigns_guards;
  "campaigns/lifecycle": typeof campaigns_lifecycle;
  "campaigns/listing": typeof campaigns_listing;
  "campaigns/organization": typeof campaigns_organization;
  "campaigns/preflight": typeof campaigns_preflight;
  "campaigns/scheduling": typeof campaigns_scheduling;
  "campaigns/send": typeof campaigns_send;
  "campaigns/sendJob": typeof campaigns_sendJob;
  "campaigns/sendQueries": typeof campaigns_sendQueries;
  "campaigns/sendVariantSplit": typeof campaigns_sendVariantSplit;
  "campaigns/statShards": typeof campaigns_statShards;
  "campaigns/testSend": typeof campaigns_testSend;
  "channels/outbound": typeof channels_outbound;
  "chat/_helpers": typeof chat__helpers;
  "chat/attachments": typeof chat_attachments;
  "chat/cleanup": typeof chat_cleanup;
  "chat/dms": typeof chat_dms;
  "chat/emailLink": typeof chat_emailLink;
  "chat/members": typeof chat_members;
  "chat/mentions": typeof chat_mentions;
  "chat/messages": typeof chat_messages;
  "chat/rooms": typeof chat_rooms;
  codeWorkTasks: typeof codeWorkTasks;
  "conditions/contact_property/index": typeof conditions_contact_property_index;
  "conditions/email_activity/index": typeof conditions_email_activity_index;
  "conditions/index": typeof conditions_index;
  "conditions/segmentMatch": typeof conditions_segmentMatch;
  "conditions/topic_membership/index": typeof conditions_topic_membership_index;
  "conditions/types": typeof conditions_types;
  confirmationEmail: typeof confirmationEmail;
  confirmationEmailQueries: typeof confirmationEmailQueries;
  "contactActivities/catalog": typeof contactActivities_catalog;
  "contactActivities/created/index": typeof contactActivities_created_index;
  "contactActivities/doi_attested/index": typeof contactActivities_doi_attested_index;
  "contactActivities/email_bounced/index": typeof contactActivities_email_bounced_index;
  "contactActivities/email_clicked/index": typeof contactActivities_email_clicked_index;
  "contactActivities/email_complained/index": typeof contactActivities_email_complained_index;
  "contactActivities/email_opened/index": typeof contactActivities_email_opened_index;
  "contactActivities/email_sent/index": typeof contactActivities_email_sent_index;
  "contactActivities/inbound_received/index": typeof contactActivities_inbound_received_index;
  "contactActivities/inbound_replied/index": typeof contactActivities_inbound_replied_index;
  "contactActivities/property_updated/index": typeof contactActivities_property_updated_index;
  "contactActivities/topic_confirmed/index": typeof contactActivities_topic_confirmed_index;
  "contactActivities/topic_subscribed/index": typeof contactActivities_topic_subscribed_index;
  "contactActivities/topic_unsubscribed/index": typeof contactActivities_topic_unsubscribed_index;
  "contactActivities/types": typeof contactActivities_types;
  "contactActivities/writer": typeof contactActivities_writer;
  "contacts/activities": typeof contacts_activities;
  "contacts/analytics": typeof contacts_analytics;
  "contacts/api": typeof contacts_api;
  "contacts/contacts": typeof contacts_contacts;
  "contacts/creation": typeof contacts_creation;
  "contacts/dataExport": typeof contacts_dataExport;
  "contacts/doiLifecycle": typeof contacts_doiLifecycle;
  "contacts/identities": typeof contacts_identities;
  "contacts/import": typeof contacts_import;
  "contacts/listing": typeof contacts_listing;
  "contacts/organization": typeof contacts_organization;
  "contacts/properties": typeof contacts_properties;
  "contacts/propertyValues": typeof contacts_propertyValues;
  "contacts/relationships": typeof contacts_relationships;
  "contacts/resolution": typeof contacts_resolution;
  "contacts/timeline": typeof contacts_timeline;
  crons: typeof crons;
  "delivery/contactToken": typeof delivery_contactToken;
  "delivery/enqueue": typeof delivery_enqueue;
  "delivery/health": typeof delivery_health;
  "delivery/messageIdRouting": typeof delivery_messageIdRouting;
  "delivery/preferences": typeof delivery_preferences;
  "delivery/preferencesHttp": typeof delivery_preferencesHttp;
  "delivery/preferencesQueries": typeof delivery_preferencesQueries;
  "delivery/sendCompletion": typeof delivery_sendCompletion;
  "delivery/sendComposition/archive_snapshot/index": typeof delivery_sendComposition_archive_snapshot_index;
  "delivery/sendComposition/automation/index": typeof delivery_sendComposition_automation_index;
  "delivery/sendComposition/campaign/index": typeof delivery_sendComposition_campaign_index;
  "delivery/sendComposition/feedbackId": typeof delivery_sendComposition_feedbackId;
  "delivery/sendComposition/index": typeof delivery_sendComposition_index;
  "delivery/sendComposition/listId": typeof delivery_sendComposition_listId;
  "delivery/sendComposition/personalization": typeof delivery_sendComposition_personalization;
  "delivery/sendComposition/plainText": typeof delivery_sendComposition_plainText;
  "delivery/sendComposition/test/index": typeof delivery_sendComposition_test_index;
  "delivery/sendComposition/trackingUrl": typeof delivery_sendComposition_trackingUrl;
  "delivery/sendComposition/transactional/index": typeof delivery_sendComposition_transactional_index;
  "delivery/sendComposition/transform": typeof delivery_sendComposition_transform;
  "delivery/sendComposition/types": typeof delivery_sendComposition_types;
  "delivery/sendLifecycle": typeof delivery_sendLifecycle;
  "delivery/sendLifecycle/effects": typeof delivery_sendLifecycle_effects;
  "delivery/sendLifecycle/feedbackReducers": typeof delivery_sendLifecycle_feedbackReducers;
  "delivery/sendLifecycle/lookups": typeof delivery_sendLifecycle_lookups;
  "delivery/sendLifecycle/reducers": typeof delivery_sendLifecycle_reducers;
  "delivery/sendLifecycle/types": typeof delivery_sendLifecycle_types;
  "delivery/sends": typeof delivery_sends;
  "delivery/status": typeof delivery_status;
  "delivery/suppressionMirror": typeof delivery_suppressionMirror;
  "delivery/tokenValidation": typeof delivery_tokenValidation;
  "delivery/tracking": typeof delivery_tracking;
  "delivery/trackingHttp": typeof delivery_trackingHttp;
  "delivery/unsubscribe": typeof delivery_unsubscribe;
  "delivery/unsubscribeHttp": typeof delivery_unsubscribeHttp;
  "delivery/unsubscribeQueries": typeof delivery_unsubscribeQueries;
  "delivery/warmingSync": typeof delivery_warmingSync;
  "delivery/worker": typeof delivery_worker;
  "delivery/workpool": typeof delivery_workpool;
  "devShortcuts/_guard": typeof devShortcuts__guard;
  "devShortcuts/forceVerifyDomain": typeof devShortcuts_forceVerifyDomain;
  "devShortcuts/reset": typeof devShortcuts_reset;
  "domains/dmarc": typeof domains_dmarc;
  "domains/dnsMatch": typeof domains_dnsMatch;
  "domains/dnsVerification": typeof domains_dnsVerification;
  "domains/domains": typeof domains_domains;
  "domains/lifecycle": typeof domains_lifecycle;
  "domains/providers/index": typeof domains_providers_index;
  "domains/providers/mta/index": typeof domains_providers_mta_index;
  "domains/providers/registerAction": typeof domains_providers_registerAction;
  "domains/providers/ses/index": typeof domains_providers_ses_index;
  "domains/providers/types": typeof domains_providers_types;
  "domains/queries": typeof domains_queries;
  "domains/reverseDns": typeof domains_reverseDns;
  "domains/spf": typeof domains_spf;
  "domains/tlsRpt": typeof domains_tlsRpt;
  "domains/trackingDomains": typeof domains_trackingDomains;
  "emailBlocks/blocks": typeof emailBlocks_blocks;
  "emailBlocks/module": typeof emailBlocks_module;
  "emailBlocks/rendering": typeof emailBlocks_rendering;
  "emailBlocks/renderingPool": typeof emailBlocks_renderingPool;
  "emailTemplates/emails": typeof emailTemplates_emails;
  "emailTemplates/i18n": typeof emailTemplates_i18n;
  "emailTemplates/lifecycle": typeof emailTemplates_lifecycle;
  "emailTemplates/listing": typeof emailTemplates_listing;
  "emailTemplates/organization": typeof emailTemplates_organization;
  "emailTemplates/translationMerge": typeof emailTemplates_translationMerge;
  eventsApi: typeof eventsApi;
  "forms/apiHttp": typeof forms_apiHttp;
  "forms/endpoints": typeof forms_endpoints;
  "forms/submission": typeof forms_submission;
  globalSearch: typeof globalSearch;
  http: typeof http;
  "inbox/askEagerness": typeof inbox_askEagerness;
  "inbox/askEagernessSettings": typeof inbox_askEagernessSettings;
  "inbox/attachmentMatch": typeof inbox_attachmentMatch;
  "inbox/attachmentSuggest": typeof inbox_attachmentSuggest;
  "inbox/attachmentValidators": typeof inbox_attachmentValidators;
  "inbox/clarification": typeof inbox_clarification;
  "inbox/clarificationLog": typeof inbox_clarificationLog;
  "inbox/clarificationMemory": typeof inbox_clarificationMemory;
  "inbox/clarificationMemoryMatch": typeof inbox_clarificationMemoryMatch;
  "inbox/clarificationSlots": typeof inbox_clarificationSlots;
  "inbox/clarificationValidators": typeof inbox_clarificationValidators;
  "inbox/messages": typeof inbox_messages;
  "inbox/mutations": typeof inbox_mutations;
  "inbox/presence": typeof inbox_presence;
  "inbox/processingLifecycle": typeof inbox_processingLifecycle;
  "inbox/processingLifecycle/autoSendCancel": typeof inbox_processingLifecycle_autoSendCancel;
  "inbox/processingLifecycle/effects": typeof inbox_processingLifecycle_effects;
  "inbox/processingLifecycle/reducers": typeof inbox_processingLifecycle_reducers;
  "inbox/processingLifecycle/types": typeof inbox_processingLifecycle_types;
  "inbox/queries": typeof inbox_queries;
  "inbox/reads": typeof inbox_reads;
  "inbox/snooze": typeof inbox_snooze;
  "inbox/stepOutputs": typeof inbox_stepOutputs;
  "inbox/threadSort": typeof inbox_threadSort;
  "inbox/threads/module": typeof inbox_threads_module;
  "integrationImports/_common": typeof integrationImports__common;
  "integrationImports/providers/index": typeof integrationImports_providers_index;
  "integrationImports/providers/mailchimp/index": typeof integrationImports_providers_mailchimp_index;
  "integrationImports/providers/stripe/index": typeof integrationImports_providers_stripe_index;
  "integrationImports/walker": typeof integrationImports_walker;
  "knowledge/edgeBackfill": typeof knowledge_edgeBackfill;
  "knowledge/edgeInference": typeof knowledge_edgeInference;
  "knowledge/edges": typeof knowledge_edges;
  "knowledge/extraction": typeof knowledge_extraction;
  "knowledge/graph": typeof knowledge_graph;
  "knowledge/graphAnalytics": typeof knowledge_graphAnalytics;
  "knowledge/graphAnalyticsRecompute": typeof knowledge_graphAnalyticsRecompute;
  "knowledge/graphTraversal": typeof knowledge_graphTraversal;
  "knowledge/maintenance": typeof knowledge_maintenance;
  "knowledge/relationDecay": typeof knowledge_relationDecay;
  "knowledge/retrieval": typeof knowledge_retrieval;
  "lib/auditLog": typeof lib_auditLog;
  "lib/authedFunctions": typeof lib_authedFunctions;
  "lib/automationConfigTypes": typeof lib_automationConfigTypes;
  "lib/autonomyRules": typeof lib_autonomyRules;
  "lib/constants": typeof lib_constants;
  "lib/contactCountHelpers": typeof lib_contactCountHelpers;
  "lib/contactHelpers": typeof lib_contactHelpers;
  "lib/contactJunctions": typeof lib_contactJunctions;
  "lib/contactMutations": typeof lib_contactMutations;
  "lib/contactScope": typeof lib_contactScope;
  "lib/convexValidators": typeof lib_convexValidators;
  "lib/cors": typeof lib_cors;
  "lib/credentialCrypto": typeof lib_credentialCrypto;
  "lib/emailAddress": typeof lib_emailAddress;
  "lib/emailHelpers": typeof lib_emailHelpers;
  "lib/emailProviders/domainVerification": typeof lib_emailProviders_domainVerification;
  "lib/emailProviders/mtaIdentity": typeof lib_emailProviders_mtaIdentity;
  "lib/emailProviders/sesIdentity": typeof lib_emailProviders_sesIdentity;
  "lib/emailTranslations": typeof lib_emailTranslations;
  "lib/env": typeof lib_env;
  "lib/featureFlags": typeof lib_featureFlags;
  "lib/graphAnalyticsCompute": typeof lib_graphAnalyticsCompute;
  "lib/graphRank": typeof lib_graphRank;
  "lib/httpResponse": typeof lib_httpResponse;
  "lib/inboundClassification": typeof lib_inboundClassification;
  "lib/inboxStats": typeof lib_inboxStats;
  "lib/inputGuards": typeof lib_inputGuards;
  "lib/ipBlocklist": typeof lib_ipBlocklist;
  "lib/knowledgeDedup": typeof lib_knowledgeDedup;
  "lib/knowledgeEdges": typeof lib_knowledgeEdges;
  "lib/knowledgePrecedence": typeof lib_knowledgePrecedence;
  "lib/listing": typeof lib_listing;
  "lib/llm/complexity": typeof lib_llm_complexity;
  "lib/llm/dispatch": typeof lib_llm_dispatch;
  "lib/llm/pricing": typeof lib_llm_pricing;
  "lib/llm/promptCache": typeof lib_llm_promptCache;
  "lib/llmProvider": typeof lib_llmProvider;
  "lib/mailHost": typeof lib_mailHost;
  "lib/mailSnooze": typeof lib_mailSnooze;
  "lib/pagination": typeof lib_pagination;
  "lib/paginationCursor": typeof lib_paginationCursor;
  "lib/posthog": typeof lib_posthog;
  "lib/posthogHelpers": typeof lib_posthogHelpers;
  "lib/publicTokenEndpoint": typeof lib_publicTokenEndpoint;
  "lib/queryHelpers": typeof lib_queryHelpers;
  "lib/randomToken": typeof lib_randomToken;
  "lib/receivedAtCursor": typeof lib_receivedAtCursor;
  "lib/rrf": typeof lib_rrf;
  "lib/runtimeLog": typeof lib_runtimeLog;
  "lib/safeCompare": typeof lib_safeCompare;
  "lib/scannerHealth": typeof lib_scannerHealth;
  "lib/secretLeakScan": typeof lib_secretLeakScan;
  "lib/sendDailyStats": typeof lib_sendDailyStats;
  "lib/sendProviders/capability": typeof lib_sendProviders_capability;
  "lib/sendProviders/dispatch": typeof lib_sendProviders_dispatch;
  "lib/sendProviders/health": typeof lib_sendProviders_health;
  "lib/sendProviders/index": typeof lib_sendProviders_index;
  "lib/sendProviders/mta/index": typeof lib_sendProviders_mta_index;
  "lib/sendProviders/resend/index": typeof lib_sendProviders_resend_index;
  "lib/sendProviders/route": typeof lib_sendProviders_route;
  "lib/sendProviders/routing": typeof lib_sendProviders_routing;
  "lib/sendProviders/ses/index": typeof lib_sendProviders_ses_index;
  "lib/sendProviders/strategies/index": typeof lib_sendProviders_strategies_index;
  "lib/sendProviders/strategies/priority_failover/index": typeof lib_sendProviders_strategies_priority_failover_index;
  "lib/sendProviders/strategies/single/index": typeof lib_sendProviders_strategies_single_index;
  "lib/sendProviders/strategies/types": typeof lib_sendProviders_strategies_types;
  "lib/sendProviders/strategies/workload_split/index": typeof lib_sendProviders_strategies_workload_split_index;
  "lib/sendProviders/types": typeof lib_sendProviders_types;
  "lib/sendingLimits": typeof lib_sendingLimits;
  "lib/sessionOrganization": typeof lib_sessionOrganization;
  "lib/ssrfGuard": typeof lib_ssrfGuard;
  "lib/statShards": typeof lib_statShards;
  "lib/suppression": typeof lib_suppression;
  "lib/systemEmails": typeof lib_systemEmails;
  "lib/tenantTables": typeof lib_tenantTables;
  "lib/textPreview": typeof lib_textPreview;
  "lib/workingHours": typeof lib_workingHours;
  "mail/ai": typeof mail_ai;
  "mail/aiCoach": typeof mail_aiCoach;
  "mail/aiGate": typeof mail_aiGate;
  "mail/aiScheduling": typeof mail_aiScheduling;
  "mail/aliases": typeof mail_aliases;
  "mail/aliasesActions": typeof mail_aliasesActions;
  "mail/appPasswords": typeof mail_appPasswords;
  "mail/authHttp": typeof mail_authHttp;
  "mail/authRateLimit": typeof mail_authRateLimit;
  "mail/availability": typeof mail_availability;
  "mail/brief": typeof mail_brief;
  "mail/category": typeof mail_category;
  "mail/categoryClassify": typeof mail_categoryClassify;
  "mail/commitmentExtract": typeof mail_commitmentExtract;
  "mail/commitments": typeof mail_commitments;
  "mail/contacts": typeof mail_contacts;
  "mail/dailyBrief": typeof mail_dailyBrief;
  "mail/delivery": typeof mail_delivery;
  "mail/deliveryHooks": typeof mail_deliveryHooks;
  "mail/draftLifecycle": typeof mail_draftLifecycle;
  "mail/draftOnArrival": typeof mail_draftOnArrival;
  "mail/draftOnArrivalStore": typeof mail_draftOnArrivalStore;
  "mail/draftStreamStore": typeof mail_draftStreamStore;
  "mail/drafts": typeof mail_drafts;
  "mail/editLearning": typeof mail_editLearning;
  "mail/editLearningValidators": typeof mail_editLearningValidators;
  "mail/externalAccounts": typeof mail_externalAccounts;
  "mail/externalAccountsActions": typeof mail_externalAccountsActions;
  "mail/externalDelivery": typeof mail_externalDelivery;
  "mail/filters": typeof mail_filters;
  "mail/folders": typeof mail_folders;
  "mail/followUps": typeof mail_followUps;
  "mail/forwarding": typeof mail_forwarding;
  "mail/handlingRules": typeof mail_handlingRules;
  "mail/handlingRules/engine": typeof mail_handlingRules_engine;
  "mail/handlingRulesCompile": typeof mail_handlingRulesCompile;
  "mail/identities": typeof mail_identities;
  "mail/imap": typeof mail_imap;
  "mail/labels": typeof mail_labels;
  "mail/mailbox": typeof mail_mailbox;
  "mail/mailboxActions": typeof mail_mailboxActions;
  "mail/mailboxQueries": typeof mail_mailboxQueries;
  "mail/messageActions": typeof mail_messageActions;
  "mail/migration": typeof mail_migration;
  "mail/migrationIndexing": typeof mail_migrationIndexing;
  "mail/mtaClient": typeof mail_mtaClient;
  "mail/needsReply": typeof mail_needsReply;
  "mail/needsReplyClarify": typeof mail_needsReplyClarify;
  "mail/needsReplyClassify": typeof mail_needsReplyClassify;
  "mail/needsReplyScoring": typeof mail_needsReplyScoring;
  "mail/outbound": typeof mail_outbound;
  "mail/outboundCron": typeof mail_outboundCron;
  "mail/outboundQueries": typeof mail_outboundQueries;
  "mail/pendingMailbox": typeof mail_pendingMailbox;
  "mail/permissions": typeof mail_permissions;
  "mail/postboxOutboundLifecycle": typeof mail_postboxOutboundLifecycle;
  "mail/priorityScore": typeof mail_priorityScore;
  "mail/replyOptions": typeof mail_replyOptions;
  "mail/reviseDraft": typeof mail_reviseDraft;
  "mail/rfc822": typeof mail_rfc822;
  "mail/settings": typeof mail_settings;
  "mail/signatures": typeof mail_signatures;
  "mail/snippets": typeof mail_snippets;
  "mail/snooze": typeof mail_snooze;
  "mail/summaryCache": typeof mail_summaryCache;
  "mail/unsubscribe": typeof mail_unsubscribe;
  "mail/vacation": typeof mail_vacation;
  "mail/voiceProfile": typeof mail_voiceProfile;
  "mail/voiceProfileActions": typeof mail_voiceProfileActions;
  "mail/voiceProfileText": typeof mail_voiceProfileText;
  "mail/webhook": typeof mail_webhook;
  "maintenance/retention": typeof maintenance_retention;
  mediaAssets: typeof mediaAssets;
  "migrations/0005_channel_generic_rename": typeof migrations_0005_channel_generic_rename;
  "migrations/0006_postbox_outbound_recipients": typeof migrations_0006_postbox_outbound_recipients;
  "migrations/0018_sending_domain_identity_sibling": typeof migrations_0018_sending_domain_identity_sibling;
  "migrations/0027_drain_inflight_integration_imports": typeof migrations_0027_drain_inflight_integration_imports;
  "migrations/0032_thread_contact_identifier": typeof migrations_0032_thread_contact_identifier;
  "migrations/0033_campaign_audience": typeof migrations_0033_campaign_audience;
  mtaWebhook: typeof mtaWebhook;
  "organizations/abuseGate": typeof organizations_abuseGate;
  "organizations/abuseStatus": typeof organizations_abuseStatus;
  "organizations/deletion/steps/_common": typeof organizations_deletion_steps__common;
  "organizations/deletion/steps/contacts": typeof organizations_deletion_steps_contacts;
  "organizations/deletion/steps/domains": typeof organizations_deletion_steps_domains;
  "organizations/deletion/steps/mailDrafts": typeof organizations_deletion_steps_mailDrafts;
  "organizations/deletion/steps/mailMessages": typeof organizations_deletion_steps_mailMessages;
  "organizations/deletion/steps/mediaAssets": typeof organizations_deletion_steps_mediaAssets;
  "organizations/deletion/steps/semanticFiles": typeof organizations_deletion_steps_semanticFiles;
  "organizations/deletion/steps/sweep": typeof organizations_deletion_steps_sweep;
  "organizations/deletion/steps/transactionalSends": typeof organizations_deletion_steps_transactionalSends;
  "organizations/deletion/walker": typeof organizations_deletion_walker;
  "organizations/featureFlags": typeof organizations_featureFlags;
  "organizations/settings": typeof organizations_settings;
  "platformAdmin/mutations": typeof platformAdmin_mutations;
  "platformAdmin/platformAdmin": typeof platformAdmin_platformAdmin;
  "platformAdmin/queries": typeof platformAdmin_queries;
  providerRoutes: typeof providerRoutes;
  publicRateLimit: typeof publicRateLimit;
  quickQuery: typeof quickQuery;
  quickQueryGate: typeof quickQueryGate;
  rateLimiter: typeof rateLimiter;
  resendWebhook: typeof resendWebhook;
  "schema/askEagerness": typeof schema_askEagerness;
  "schema/assistant": typeof schema_assistant;
  "schema/auth": typeof schema_auth;
  "schema/automations": typeof schema_automations;
  "schema/autonomy": typeof schema_autonomy;
  "schema/campaigns": typeof schema_campaigns;
  "schema/chat": typeof schema_chat;
  "schema/codeWork": typeof schema_codeWork;
  "schema/contacts": typeof schema_contacts;
  "schema/dashboard": typeof schema_dashboard;
  "schema/delivery": typeof schema_delivery;
  "schema/domains": typeof schema_domains;
  "schema/draftStream": typeof schema_draftStream;
  "schema/forms": typeof schema_forms;
  "schema/inbox": typeof schema_inbox;
  "schema/integrations": typeof schema_integrations;
  "schema/knowledge": typeof schema_knowledge;
  "schema/mail": typeof schema_mail;
  "schema/messaging": typeof schema_messaging;
  "schema/templates": typeof schema_templates;
  "schema/topics": typeof schema_topics;
  "schema/webhooks": typeof schema_webhooks;
  seedAdmin: typeof seedAdmin;
  "seedDemo/index": typeof seedDemo_index;
  "seedDemo/loaders/accounts": typeof seedDemo_loaders_accounts;
  "seedDemo/loaders/automations": typeof seedDemo_loaders_automations;
  "seedDemo/loaders/campaigns": typeof seedDemo_loaders_campaigns;
  "seedDemo/loaders/contactTopics": typeof seedDemo_loaders_contactTopics;
  "seedDemo/loaders/contacts": typeof seedDemo_loaders_contacts;
  "seedDemo/loaders/domains": typeof seedDemo_loaders_domains;
  "seedDemo/loaders/emailTemplates": typeof seedDemo_loaders_emailTemplates;
  "seedDemo/loaders/savedBlocks": typeof seedDemo_loaders_savedBlocks;
  "seedDemo/loaders/topics": typeof seedDemo_loaders_topics;
  "seedDemo/loaders/types": typeof seedDemo_loaders_types;
  "seedDemo/loaders/webhooks": typeof seedDemo_loaders_webhooks;
  segments: typeof segments;
  "segments/listing": typeof segments_listing;
  semanticFileProcessing: typeof semanticFileProcessing;
  semanticFiles: typeof semanticFiles;
  shareLinkHttp: typeof shareLinkHttp;
  shareLinkQueries: typeof shareLinkQueries;
  shareLinks: typeof shareLinks;
  storage: typeof storage;
  systemHealth: typeof systemHealth;
  systemMail: typeof systemMail;
  systemUpdates: typeof systemUpdates;
  "topics/apiHttp": typeof topics_apiHttp;
  "topics/bulk": typeof topics_bulk;
  "topics/doiHttp": typeof topics_doiHttp;
  "topics/listing": typeof topics_listing;
  "topics/subscription": typeof topics_subscription;
  "topics/topics": typeof topics_topics;
  "transactional/api": typeof transactional_api;
  "transactional/dispatch": typeof transactional_dispatch;
  "transactional/emails": typeof transactional_emails;
  "transactional/lifecycle": typeof transactional_lifecycle;
  "transactional/sends": typeof transactional_sends;
  "transactional/translations": typeof transactional_translations;
  translate: typeof translate;
  unifiedMessages: typeof unifiedMessages;
  visualizationAgent: typeof visualizationAgent;
  "webhooks/adapters/generic": typeof webhooks_adapters_generic;
  "webhooks/adapters/meta": typeof webhooks_adapters_meta;
  "webhooks/adapters/mta": typeof webhooks_adapters_mta;
  "webhooks/adapters/resend": typeof webhooks_adapters_resend;
  "webhooks/adapters/twilio": typeof webhooks_adapters_twilio;
  "webhooks/channels": typeof webhooks_channels;
  "webhooks/cleanup": typeof webhooks_cleanup;
  "webhooks/delivery": typeof webhooks_delivery;
  "webhooks/deliveryQueries": typeof webhooks_deliveryQueries;
  "webhooks/dispatcher": typeof webhooks_dispatcher;
  "webhooks/endpoints": typeof webhooks_endpoints;
  "webhooks/events": typeof webhooks_events;
  "webhooks/events/contactCreated/index": typeof webhooks_events_contactCreated_index;
  "webhooks/events/emailBounced/index": typeof webhooks_events_emailBounced_index;
  "webhooks/events/emailClicked/index": typeof webhooks_events_emailClicked_index;
  "webhooks/events/emailComplained/index": typeof webhooks_events_emailComplained_index;
  "webhooks/events/emailDelivered/index": typeof webhooks_events_emailDelivered_index;
  "webhooks/events/emailOpened/index": typeof webhooks_events_emailOpened_index;
  "webhooks/events/emailSent/index": typeof webhooks_events_emailSent_index;
  "webhooks/events/registry": typeof webhooks_events_registry;
  "webhooks/events/test/index": typeof webhooks_events_test_index;
  "webhooks/events/topicUnsubscribed/index": typeof webhooks_events_topicUnsubscribed_index;
  "webhooks/fanout": typeof webhooks_fanout;
  "webhooks/githubHttp": typeof webhooks_githubHttp;
  "webhooks/payloads": typeof webhooks_payloads;
  "webhooks/pipeline": typeof webhooks_pipeline;
  "webhooks/scheduleFanout": typeof webhooks_scheduleFanout;
  "webhooks/security": typeof webhooks_security;
  "webhooks/types": typeof webhooks_types;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  transactionalEmailPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"transactionalEmailPool">;
  campaignEmailPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"campaignEmailPool">;
  rerenderBlocksPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"rerenderBlocksPool">;
};
