/**
 * MTA transport-secret sealing (secrets at rest).
 *
 * This is the MTA-local twin of the Convex `createSecretBox` primitive
 * (apps/api/convex/lib/credentialCrypto.ts): the SAME AES-256-GCM + HKDF-SHA256
 * core, parameterized by an explicit domain-separation context. It is
 * re-implemented here rather than imported because the Convex module is a
 * `'use node'` action file that imports Convex-only helpers (`./env`,
 * `./constants`); importing it into the MTA would drag in the Convex runtime and
 * would also cross the package boundary the cross-package-import guard forbids.
 *
 * The box is keyed by MTA_SECRET (declared + boot-validated in
 * apps/mta/src/config.ts, generated by the installer). Its HKDF context labels
 * are DISTINCT from every other consumer (external-mail creds, keyVault) so the
 * derived key stays cryptographically isolated — a value sealed here can never
 * open under another box.
 *
 * The first consumer is the DKIM key store (smtp/dkimStore.ts), which seals
 * private-key PEMs on write and unseals them on read.
 */

import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from 'crypto';

const ALGORITHM = 'aes-256-gcm';
const KEY_BYTES = 32;
const IV_BYTES = 12; // GCM standard 96-bit nonce
const AUTH_TAG_BYTES = 16; // GCM standard 128-bit auth tag (passed explicitly)

/**
 * The minimum MTA_SECRET length. A 32-byte key is the floor for AES-256-derived
 * material; a shorter secret is refused at boot so we never seal under a weak key.
 */
export const MTA_SECRET_MIN_BYTES = 32;

/**
 * The HKDF domain-separation context for the MTA transport-secret box. Changing
 * either label is a KDF change that would strand every value already sealed
 * under the old labels — bump the `:v1` suffix and add a re-seal migration.
 */
const MTA_SECRET_SALT = 'owlat:mta-secrets:salt:v1';
const MTA_SECRET_INFO = 'owlat:mta-secrets:secrets:v1';

/**
 * The prefix every sealed value carries. It lets the reader distinguish a sealed
 * envelope from a legacy plaintext value (e.g. a PEM private key) so plaintext
 * can be detected and migrated in place. The `:v1:` marks the envelope layout.
 */
const SEALED_PREFIX = 'mtasealed:v1:';

/** Two boxes with different labels derive independent keys (cross-context isolation). */
export interface SecretBoxContext {
	/** HKDF salt — the version-pinned separation label. */
	salt: string;
	/** HKDF info — the per-use separation label. */
	info: string;
}

/** A reusable AES-256-GCM + HKDF-SHA256 sealing primitive. */
export interface SecretBox {
	/** Seal a plaintext string into a self-describing sealed token (with prefix). */
	seal(plaintext: string): string;
	/** Open a sealed token back to plaintext. Throws on a bad prefix or auth-tag mismatch (tamper / wrong key). */
	open(sealed: string): string;
	/** Whether a stored value is a sealed token produced by {@link seal}. */
	isSealed(value: string): boolean;
}

/**
 * Build a {@link SecretBox} that derives its key from `secret` under the given
 * HKDF salt/info context. Pure crypto — reads no env — so callers control the
 * secret source and the domain-separation labels.
 */
export function createSecretBox(secret: string, context: SecretBoxContext): SecretBox {
	const deriveKey = (): Buffer => {
		const derived = hkdfSync(
			'sha256',
			Buffer.from(secret, 'utf8'),
			Buffer.from(context.salt, 'utf8'),
			Buffer.from(context.info, 'utf8'),
			KEY_BYTES
		);
		return Buffer.from(derived);
	};

	const isSealed = (value: string): boolean => value.startsWith(SEALED_PREFIX);

	return {
		isSealed,
		seal(plaintext: string): string {
			const key = deriveKey();
			const iv = randomBytes(IV_BYTES);
			const cipher = createCipheriv(ALGORITHM, key, iv, { authTagLength: AUTH_TAG_BYTES });
			const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
			const authTag = cipher.getAuthTag();
			return (
				SEALED_PREFIX +
				`${iv.toString('base64')}.${authTag.toString('base64')}.${ciphertext.toString('base64')}`
			);
		},
		open(sealed: string): string {
			if (!isSealed(sealed)) {
				throw new Error('secretBox.open: value is not a sealed token');
			}
			const body = sealed.slice(SEALED_PREFIX.length);
			const parts = body.split('.');
			if (parts.length !== 3) {
				throw new Error('secretBox.open: malformed sealed token');
			}
			const [ivB64, tagB64, ctB64] = parts as [string, string, string];
			const key = deriveKey();
			const iv = Buffer.from(ivB64, 'base64');
			const decipher = createDecipheriv(ALGORITHM, key, iv, { authTagLength: AUTH_TAG_BYTES });
			decipher.setAuthTag(Buffer.from(tagB64, 'base64'));
			const plaintext = Buffer.concat([
				decipher.update(Buffer.from(ctB64, 'base64')),
				decipher.final(),
			]);
			return plaintext.toString('utf8');
		},
	};
}

/**
 * Assert an MTA_SECRET is present and strong enough (>= 32 bytes). Called at
 * config load so a weak/absent secret fails the boot fast rather than sealing
 * transport secrets under a guessable key.
 *
 * @throws Error when the secret is missing or shorter than {@link MTA_SECRET_MIN_BYTES}.
 */
export function assertMtaSecretStrength(secret: string | undefined): asserts secret is string {
	if (!secret) {
		throw new Error(
			'MTA_SECRET is required — it seals DKIM keys and transport credentials at rest.'
		);
	}
	if (Buffer.byteLength(secret, 'utf8') < MTA_SECRET_MIN_BYTES) {
		throw new Error(
			`MTA_SECRET must be at least ${MTA_SECRET_MIN_BYTES} bytes; got ${Buffer.byteLength(secret, 'utf8')}.`
		);
	}
}

let cachedBox: SecretBox | null = null;

/**
 * The MTA transport-secret box: MTA_SECRET under the pinned MTA context. Lazily
 * built and cached. Reads MTA_SECRET from the environment (config.ts validates
 * its presence + strength at boot); throws here too if it is missing/weak so a
 * misconfigured process can never seal under a bad key.
 */
export function getMtaSecretBox(): SecretBox {
	if (cachedBox) return cachedBox;
	const secret = process.env['MTA_SECRET'];
	assertMtaSecretStrength(secret);
	cachedBox = createSecretBox(secret, { salt: MTA_SECRET_SALT, info: MTA_SECRET_INFO });
	return cachedBox;
}

/** Reset the cached box (tests only, after mutating MTA_SECRET). */
export function resetMtaSecretBoxForTests(): void {
	cachedBox = null;
}
