/**
 * MTA transport-secret sealing (secrets at rest).
 *
 * A thin binding of the shared `createSecretBox` primitive
 * (`@owlat/shared/secretBox`) under the MTA's own domain-separation context. The
 * AES-256-GCM + HKDF-SHA256 core lives in `@owlat/shared` so every "seal a secret
 * on disk" consumer (this box + the `.env`-backup box) shares one crypto surface;
 * this module only pins the MTA labels and manages the boot-bound singleton.
 *
 * The box is keyed by MTA_SECRET (declared + boot-validated in
 * apps/mta/src/config.ts, generated by the installer). Its HKDF context labels
 * are DISTINCT from every other consumer (external-mail creds, `.env` backup,
 * keyVault) so the derived key stays cryptographically isolated — a value sealed
 * here can never open under another box.
 *
 * The first consumer is the DKIM key store (smtp/dkimStore.ts), which seals
 * private-key PEMs on write and unseals them on read.
 */

import { createSecretBox as createSharedSecretBox, type SecretBox } from '@owlat/shared/secretBox';

export type { SecretBox } from '@owlat/shared/secretBox';

/**
 * The minimum MTA_SECRET length. A 32-byte key is the floor for AES-256-derived
 * material; a shorter secret is refused at boot so we never seal under a weak key.
 */
export const MTA_SECRET_MIN_BYTES = 32;

/**
 * The HKDF domain-separation context for the MTA transport-secret box. Changing
 * either label is a KDF change that would strand every value already sealed
 * under the old labels — bump the `:v1` suffix and add a re-seal migration.
 */
const MTA_SECRET_SALT = 'owlat:mta-secrets:salt:v1';
const MTA_SECRET_INFO = 'owlat:mta-secrets:secrets:v1';

/**
 * The prefix every sealed value carries. It lets the reader distinguish a sealed
 * envelope from a legacy plaintext value (e.g. a PEM private key) so plaintext
 * can be detected and migrated in place. The `:v1:` marks the envelope layout.
 */
const SEALED_PREFIX = 'mtasealed:v1:';

/** The MTA-local domain-separation context (salt/info); the prefix is pinned here. */
export interface SecretBoxContext {
	/** HKDF salt — the version-pinned separation label. */
	salt: string;
	/** HKDF info — the per-use separation label. */
	info: string;
}

/**
 * Build a {@link SecretBox} that derives its key from `secret` under the given
 * MTA salt/info context and the pinned `mtasealed:v1:` prefix. A thin binding of
 * the shared primitive — pure crypto, reads no env.
 */
export function createSecretBox(secret: string, context: SecretBoxContext): SecretBox {
	return createSharedSecretBox(secret, { ...context, prefix: SEALED_PREFIX });
}

/**
 * Assert an MTA_SECRET is present and strong enough (>= 32 bytes). Called at
 * config load so a weak/absent secret fails the boot fast rather than sealing
 * transport secrets under a guessable key.
 *
 * @throws Error when the secret is missing or shorter than {@link MTA_SECRET_MIN_BYTES}.
 */
export function assertMtaSecretStrength(secret: string | undefined): asserts secret is string {
	if (!secret) {
		throw new Error(
			'MTA_SECRET is required — it seals DKIM keys and transport credentials at rest.'
		);
	}
	if (Buffer.byteLength(secret, 'utf8') < MTA_SECRET_MIN_BYTES) {
		throw new Error(
			`MTA_SECRET must be at least ${MTA_SECRET_MIN_BYTES} bytes; got ${Buffer.byteLength(secret, 'utf8')}.`
		);
	}
}

let cachedBox: SecretBox | null = null;

/**
 * Bind the MTA transport-secret box to the boot-validated secret from config.
 *
 * Called once from the MTA entry point with `config.mtaSecret` so the env read
 * lives in `config.ts` (the single MTA env boundary) and the box has ONE
 * authoritative secret source in production. `getMtaSecretBox()` then returns
 * this bound box rather than re-reading the environment.
 */
export function initMtaSecretBox(secret: string): void {
	assertMtaSecretStrength(secret);
	cachedBox = createSecretBox(secret, { salt: MTA_SECRET_SALT, info: MTA_SECRET_INFO });
}

/**
 * The MTA transport-secret box: MTA_SECRET under the pinned MTA context.
 *
 * In production it is bound at boot by {@link initMtaSecretBox} from
 * `config.mtaSecret`. If that has not run (unit tests that seal/unseal without
 * loading the full config), it lazily falls back to `MTA_SECRET` from the
 * environment — validated for presence + strength either way, so a misconfigured
 * process can never seal under a weak key.
 */
export function getMtaSecretBox(): SecretBox {
	if (cachedBox) return cachedBox;
	const secret = process.env['MTA_SECRET'];
	assertMtaSecretStrength(secret);
	cachedBox = createSecretBox(secret, { salt: MTA_SECRET_SALT, info: MTA_SECRET_INFO });
	return cachedBox;
}

/** Reset the cached box (tests only, after mutating MTA_SECRET). */
export function resetMtaSecretBoxForTests(): void {
	cachedBox = null;
}
