/**
 * Generate a Caddyfile for a domain-based install.
 *
 * When the operator provides public URLs (`SetupConfig.network`), the stack runs
 * behind Caddy (the `tls` compose profile) which terminates HTTPS and reverse
 * proxies to the web app + Convex. This produces that config from the three
 * public hostnames — mirroring `Caddyfile.example`, but parameterized so it works
 * for any naming the URLs imply (not just the `owlat./convex./convex-site.`
 * convention). Caddy auto-provisions Let's Encrypt certs for each host on boot;
 * the operator must point DNS at the box and open 80/443.
 */

export interface CaddyfileOptions {
	/** Host serving the web UI (proxied to web:3000). */
	webHost: string;
	/** Host serving the Convex sync/cloud port (proxied to convex:3210). */
	convexHost: string;
	/** Host serving the Convex site/HTTP-actions port (proxied to convex:3211). */
	convexSiteHost: string;
	/** Email used for the Let's Encrypt account. */
	email: string;
}

const SECURITY_HEADERS = `	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		-Server
	}`;

export function buildCaddyfile(o: CaddyfileOptions): string {
	return `# Generated by owlat-setup — do not edit by hand (re-run setup to regenerate).
{
	email ${o.email}
	servers {
		protocols h1 h2 h3
	}
}

# ── Web UI ───────────────────────────────────────────────────────────────────
${o.webHost} {
	reverse_proxy web:3000
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Frame-Options "SAMEORIGIN"
		X-Content-Type-Options "nosniff"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}
	encode gzip zstd
}

# ── Convex backend (browser-facing WebSocket + HTTP) ─────────────────────────
${o.convexHost} {
	reverse_proxy convex:3210
	# Convex WebSocket needs longer timeouts.
	reverse_proxy /api/* convex:3210 {
		transport http {
			read_timeout 600s
			write_timeout 600s
		}
	}
${SECURITY_HEADERS}
	encode gzip zstd
}

# ── Convex site routes (HTTP actions — BetterAuth, webhooks, tracking) ───────
${o.convexSiteHost} {
	reverse_proxy convex:3211
${SECURITY_HEADERS}
	encode gzip zstd
}
`;
}
