/**
 * Generate docker-compose.override.yml selecting the active profiles for the
 * resolved feature flag state. The base compose file (the repo-root docker-compose.yml)
 * has `profiles:` declared on every gated service; the override turns them on.
 *
 * Compose ignores unknown profile names, so this is forward-compatible: adding
 * a new flag with a new profile only requires updating featureFlags.ts.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import {
	getActiveProfiles,
	type FeatureFlagState,
} from '@owlat/shared/featureFlags';

/**
 * The built-in MTA is opt-in: its `mta` compose profile activates when MTA is
 * the delivery provider (env-driven, not a flag) or when postbox/inbox need it.
 * The provider lives in `.env` (EMAIL_PROVIDER), co-located with the override —
 * read it as a fallback so post-setup flag toggles still keep the MTA running
 * for an MTA deployment. Best-effort: a missing/unparseable .env returns undefined.
 */
async function readDeliveryProvider(overridePath: string): Promise<string | undefined> {
	try {
		const envText = await readFile(join(dirname(overridePath), '.env'), 'utf-8');
		const match = envText.match(/^\s*EMAIL_PROVIDER\s*=\s*(.+?)\s*$/m);
		return match?.[1]?.replace(/^["']|["']$/g, '');
	} catch {
		return undefined;
	}
}

export async function writeComposeOverride(
	path: string,
	flags: FeatureFlagState,
	opts: { hosted?: boolean; deliveryProvider?: string } = {}
): Promise<string[]> {
	const deliveryProvider = opts.deliveryProvider ?? (await readDeliveryProvider(path));
	const profiles = getActiveProfiles(flags, { ...opts, deliveryProvider });

	const doc = {
		// Compose-spec 'version' is no longer required; omitted for compose v2.
		// `x-` extensions document the source so operators can trace why a service is running.
		'x-owlat-profiles': profiles,
		'x-owlat-generated-at': new Date().toISOString(),
		services: Object.fromEntries(
			profiles.map((p) => [
				`__${p}_marker`,
				{
					// Synthetic marker service — compose ignores keys it doesn't recognize,
					// so this just records the activation. The actual gating is via the
					// `--profile <name>` flag passed to `docker compose up`.
					image: 'busybox:stable',
					command: 'true',
					profiles: [p],
					restart: 'no',
				},
			])
		),
	};

	const yaml = `# Generated by owlat-setup. DO NOT EDIT MANUALLY.\n# Active profiles: ${profiles.join(', ') || '(none)'}\n\n${yamlStringify(doc)}`;
	await writeFile(path, yaml, 'utf-8');
	return profiles;
}

/**
 * Build the COMPOSE_PROFILES env var string passed to docker compose.
 * Use this when you don't want a marker file — just the comma-separated list.
 */
export function buildComposeProfilesEnv(
	flags: FeatureFlagState,
	opts: { hosted?: boolean; deliveryProvider?: string } = {},
): string {
	return getActiveProfiles(flags, opts).join(',');
}
