/**
 * The refinement contract — stage 2 of the Reply Queue signal (stage 1 is the
 * deterministic screen in mail/needsReplyHeuristic.ts): the reply-intent
 * taxonomy, the prompt that asks for it, the rule that turns the answer into a
 * queue verdict, and the normalizers that bound the model's other fields before
 * they are persisted. All of it pure, so the whole contract unit-tests without
 * a live model; mail/ai/needsReplyClassify.ts keeps only the Convex action.
 *
 * WHY AN INTENT AND NOT A BOOLEAN. The refinement pass used to ask the model a
 * single question — "does this need a reply?" — and trust the answer. A cheap
 * model answers that question by looking for anything actionable, so an
 * auto-generated meeting-notes mail full of "Me: clarify billing with Markus"
 * bullets came back `true`: the reader does have work to do, it just isn't
 * *answering an email*. The queue then offered a draft reply to a notes robot.
 *
 * So the model is asked to NAME the message instead, from a closed taxonomy it
 * can judge one item at a time, and this module — not the model — decides which
 * names belong in the queue. Both must agree: the model's boolean is kept as a
 * veto (it may know the reader was only Cc-ed into a question), but it can no
 * longer promote an FYI, a recap or a receipt on its own.
 *
 * Pure (no Convex, no SDK) so the taxonomy, the decision rule and the prompt
 * are all unit-testable without a live model.
 */

/**
 * What the last inbound message IS, from the sender's point of view. Closed set
 * — the model picks exactly one, and every name has to be distinguishable from
 * a two-line excerpt or the cheap tier will smear them together.
 */
export const REPLY_INTENTS = [
	/** Asks the reader something and waits for the answer. */
	'direct_question',
	/** Asks the reader to do, send, review or confirm something. */
	'request_for_action',
	/** Needs the reader's approval/sign-off before the sender proceeds. */
	'approval_or_decision',
	/** Proposes or asks about a meeting time. */
	'scheduling',
	/** A person writing personally, where silence would read as rude. */
	'personal_message',
	/** FYI: notes, minutes, recaps, status, shared docs, announcements. */
	'informational_update',
	/** Generated by a system: alerts, CI results, sign-in notices, reports. */
	'automated_notification',
	/** Order, invoice, payment, shipping or subscription confirmation. */
	'transactional_receipt',
	/** Newsletter, digest, marketing or mass announcement. */
	'broadcast',
	/** Closes the conversation ("thanks!", "got it") and needs nothing back. */
	'acknowledgement',
] as const;

export type ReplyIntent = (typeof REPLY_INTENTS)[number];

/**
 * The intents that put a thread in the Reply Queue. Everything else is mail the
 * reader should READ, not answer — and the queue is a list of replies owed, not
 * a second inbox.
 */
const REPLY_EXPECTING_INTENTS: ReadonlySet<ReplyIntent> = new Set<ReplyIntent>([
	'direct_question',
	'request_for_action',
	'approval_or_decision',
	'scheduling',
	'personal_message',
]);

/** True when an intent means the sender is waiting on an email back. */
export function isReplyExpectingIntent(intent: ReplyIntent): boolean {
	return REPLY_EXPECTING_INTENTS.has(intent);
}

export type ReplySuppressionReason = 'intent' | 'model' | 'unattended_sender';

export interface ReplyDecision {
	needsReply: boolean;
	/** Why the row was kept out — for tests and for reading logs later. */
	suppressedBy?: ReplySuppressionReason;
}

/**
 * The queue verdict: the model's boolean AND a reply-expecting intent AND a
 * sender who can actually receive the reply.
 *
 * `isUnattendedSender` is re-checked here even though the deterministic screen
 * already rejects those addresses, because the screen only sees the ingest-time
 * headers on the ingest path — the reconcile sweep re-classifies without them,
 * and a model that decides a no-reply robot "asked a question" must not be able
 * to queue a reply nobody will read.
 */
export function decideNeedsReply(input: {
	intent: ReplyIntent;
	/** The model's own needsReply boolean (kept as a veto). */
	modelNeedsReply: boolean;
	/** The trigger message came from an unattended/no-reply address. */
	isUnattendedSender: boolean;
}): ReplyDecision {
	if (input.isUnattendedSender) return { needsReply: false, suppressedBy: 'unattended_sender' };
	if (!isReplyExpectingIntent(input.intent)) return { needsReply: false, suppressedBy: 'intent' };
	if (!input.modelNeedsReply) return { needsReply: false, suppressedBy: 'model' };
	return { needsReply: true };
}

/**
 * The taxonomy as the model reads it. Kept next to the type so a new intent
 * cannot be added without its one-line definition.
 */
const INTENT_GUIDE = [
	'- direct_question: asks the reader something and is waiting for the answer',
	'- request_for_action: asks the reader to do, send, review, confirm or fix something',
	'- approval_or_decision: needs the reader to approve, sign off or choose before the sender can proceed',
	'- scheduling: proposes, asks about or confirms a meeting time with the reader',
	'- personal_message: a person writing to the reader personally (congratulations, condolences, catching up), where not answering would be rude',
	'- informational_update: sent so the reader KNOWS something — meeting notes, minutes, recaps, summaries, transcripts, recordings, status updates, shared documents, announcements, "no action needed" mail',
	'- automated_notification: generated by a system or app — alerts, CI or deploy results, sign-in notices, calendar notifications, delivery reports',
	'- transactional_receipt: order, invoice, payment, shipping or subscription confirmation',
	'- broadcast: newsletter, digest, marketing or mass announcement',
	'- acknowledgement: closes the conversation ("thanks!", "got it", "sounds good") and needs nothing back',
].join('\n');

/**
 * The rules the cheap tier gets wrong without being told. Each one is a real
 * misclassification the queue shipped: the recap rule is the meeting-notes bug
 * this taxonomy was written for.
 */
const DECISION_RULES = [
	'- Action items, to-dos or next steps listed INSIDE a recap, summary, meeting-notes or status mail do NOT make it reply-expecting. The reader does that work; they do not answer the mail. Name it informational_update.',
	'- A message from an unattended address (no-reply, notifications@, a notes/digest robot) is never reply-expecting, even when it lists tasks or asks a rhetorical question.',
	'- Closing politeness ("let me know if you have questions", "hope this helps", "happy to discuss") is not a request.',
	'- A question aimed at someone else in the thread, or one the sender already answered, does not need a reply FROM THE READER.',
	'- A meeting the sender only reports on (notes, recording, "as discussed") is not scheduling; scheduling means a time still has to be agreed with the reader.',
	'- When torn between informational and reply-expecting, ask whether the sender is sitting there waiting for an email back. If not, it is informational.',
] as const;

/**
 * Build the refinement prompt. `systemGuard` is prepended verbatim — the thread
 * is attacker-controlled inbound mail and stays framed as untrusted DATA.
 */
export function buildReplyIntentPrompt(opts: {
	systemGuard: string;
	ownerAddress: string;
	transcript: string;
	/** The sender looks like a publishing/automated address (weak hint). */
	senderLooksAutomated: boolean;
}): string {
	const senderNote = opts.senderLooksAutomated
		? `\n\nThe sending address looks like an automated/publishing mailbox rather than a person, so a reply to it may well reach nobody.`
		: '';
	return (
		`${opts.systemGuard}\n\n` +
		`The reader is ${opts.ownerAddress}. Look at the LAST inbound message in this thread.\n\n` +
		`First name what that message IS, as exactly one intent:\n${INTENT_GUIDE}\n\n` +
		`Then set needsReply: true only when the sender is waiting for an email back FROM THE READER ` +
		`(so only for direct_question, request_for_action, approval_or_decision, scheduling or ` +
		`personal_message), and the reader — not someone else on the thread — is the one expected to ` +
		`answer. Reading it, filing it, or doing a task it mentions is not replying.\n\n` +
		`Rules:\n${DECISION_RULES.join('\n')}\n\n` +
		`Also give: urgency (high/normal/low); askSummary, a one-line "what they are asking" of at most ` +
		`120 characters (null unless needsReply is true); dueHint as an ISO date (YYYY-MM-DD) only if the ` +
		`message states a concrete deadline, else null; and meetingIntent when the sender is trying to ` +
		`SCHEDULE a meeting/call in prose (isScheduling true), capturing proposedTimes as the sender's ` +
		`VERBATIM phrases (e.g. "Tuesday afternoon", "after 3pm") plus an optional short topic — null ` +
		`when the message is not about scheduling.` +
		senderNote +
		`\n\nThread:\n\n${opts.transcript}`
	);
}

// ─── Bounding the model's other fields ──────────────────────────────────────

/** Keep only a parseable ISO-like date hint; drop hallucinated formats. */
export function normalizeDueHint(raw: string | null): string | undefined {
	if (!raw) return undefined;
	const trimmed = raw.trim();
	if (!/^\d{4}-\d{2}-\d{2}/.test(trimmed)) return undefined;
	return Number.isNaN(Date.parse(trimmed)) ? undefined : trimmed.slice(0, 10);
}

const MAX_PROPOSED_TIMES = 6;
const MAX_TIME_PHRASE_CHARS = 80;
const MAX_TOPIC_CHARS = 120;

interface MeetingIntent {
	isScheduling: boolean;
	proposedTimes: string[];
	topic?: string;
}

/**
 * Coerce the LLM's raw meetingIntent into the bounded persisted shape, or
 * `undefined` when there is nothing to show. Returns `undefined` when the
 * trigger message already carries a calendar invite (.ics) — that path is
 * owned by PostboxInviteCard, and the plain-prose chip must never double up on
 * it. Pure + exported so it unit-tests without a live model or Convex.
 */
export function normalizeMeetingIntent(
	raw: { isScheduling: boolean; proposedTimes: string[]; topic: string | null } | null,
	opts: { hasCalendarInvite: boolean }
): MeetingIntent | undefined {
	if (opts.hasCalendarInvite) return undefined;
	if (!raw || !raw.isScheduling) return undefined;
	const proposedTimes = (raw.proposedTimes ?? [])
		.map((t) => t.trim().slice(0, MAX_TIME_PHRASE_CHARS))
		.filter((t) => t.length > 0)
		.slice(0, MAX_PROPOSED_TIMES);
	const topic = raw.topic?.trim().slice(0, MAX_TOPIC_CHARS) || undefined;
	return { isScheduling: true, proposedTimes, topic };
}
