export const GENERATED_HEADER = `// Generated by @owlat/plugin-codegen. Do not edit by hand.\n// Run \`bun run plugins:codegen\` after changing plugins.config.ts.\n`;

/** One ordered plugin contribution whose executable module is imported by kind. */
export interface PluginModuleFileEntry {
	readonly packageName: string;
	readonly pluginId: string;
	readonly kind: string;
	readonly exportPath: string;
}

export interface PluginModuleFileSpec {
	/** Local import identifier prefix, suffixed by the entry index. */
	readonly varPrefix: string;
	/** plugin-kit contract each imported module is checked against with `satisfies`. */
	readonly contract: string;
	/** Exported `Object.freeze([...])` constant name. */
	readonly modulesConst: string;
	/** Whether the module list runs inside a Convex action (`'use node'`). */
	readonly useNode: boolean;
}

/**
 * Render a `Kind -> executable module` registry file: default imports keyed by
 * index, each frozen entry checked against its contract with `satisfies`, a
 * conditional contract import, an optional `'use node'` prologue, and an
 * empty-freeze fallback. Shared by every hosted registry that ships executable
 * modules (automation trigger/step/condition, import providers) so the emitted
 * shape stays identical across them.
 */
export function renderPluginModuleFile(
	entries: readonly PluginModuleFileEntry[],
	spec: PluginModuleFileSpec
): string {
	const imports = entries
		.map(
			(entry, index) =>
				`import ${spec.varPrefix}${index} from ${JSON.stringify(`${entry.packageName}${entry.exportPath.slice(1)}`)};`
		)
		.join('\n');
	const body = entries
		.map(
			(entry, index) =>
				`\tObject.freeze({ kind: ${JSON.stringify(entry.kind)}, pluginId: ${JSON.stringify(entry.pluginId)}, module: ${spec.varPrefix}${index} satisfies ${spec.contract} }),`
		)
		.join('\n');
	const modules = body ? `Object.freeze([\n${body}\n] as const)` : 'Object.freeze([] as const)';
	const contractImport = entries.length
		? `import type { ${spec.contract} } from '@owlat/plugin-kit';\n`
		: '';
	const prologue = spec.useNode ? "'use node';\n\n" : '';
	return `${prologue}${GENERATED_HEADER}${contractImport}${imports}${imports ? '\n\n' : ''}export const ${spec.modulesConst} = ${modules};\n`;
}
