import { parsePluginPackageName, type BundledPlugin } from '@owlat/plugin-host';
import { parsePluginId } from '@owlat/plugin-kit';

const GENERATED_HEADER = `// Generated by @owlat/plugin-codegen. Do not edit by hand.\n// Run \`bun run plugins:codegen\` after changing plugins.config.ts.\n`;

export interface GeneratedPluginComposition {
	readonly convex: string;
	readonly components: string;
	readonly nuxt: string;
}

export function renderPluginComposition(
	plugins: readonly BundledPlugin[]
): GeneratedPluginComposition {
	const imports = plugins
		.map((plugin, index) => {
			const packageName = JSON.stringify(parsePluginPackageName(plugin.packageName));
			return `import bundledPluginManifest${index} from ${packageName};`;
		})
		.join('\n');
	const sources = plugins
		.map((plugin, index) => {
			const packageName = JSON.stringify(parsePluginPackageName(plugin.packageName));
			return `\t{ packageName: ${packageName}, manifest: bundledPluginManifest${index} },`;
		})
		.join('\n');
	const composition = sources
		? `export const bundledPluginComposition = composeBundledPlugins([\n${sources}\n]);\n`
		: 'export const bundledPluginComposition = composeBundledPlugins([]);\n';
	const shared = `${GENERATED_HEADER}import { composeBundledPlugins } from '@owlat/plugin-host';\n${imports}${imports ? '\n' : ''}\n${composition}`;

	return Object.freeze({
		convex: shared,
		components: renderConvexComponents(plugins),
		nuxt: `${shared}\nexport default defineNuxtPlugin({\n\tname: 'owlat:bundled-plugin-composition',\n\tsetup() {\n\t\tvoid bundledPluginComposition;\n\t},\n});\n`,
	});
}

function renderConvexComponents(plugins: readonly BundledPlugin[]): string {
	const components = plugins.flatMap((plugin) => {
		const component = plugin.manifest.component;
		if (!component) return [];
		const packageName = parsePluginPackageName(plugin.packageName);
		const pluginId = parsePluginId(plugin.manifest.id);
		return [
			{
				moduleSpecifier: `${packageName}${component.exportPath.slice(1)}`,
				namespace: convexComponentNamespace(pluginId),
			},
		];
	});
	const imports = components
		.map(
			(component, index) =>
				`import bundledPluginComponent${index} from ${JSON.stringify(component.moduleSpecifier)};`
		)
		.join('\n');
	const registrations = components
		.map(
			(component, index) =>
				`\tapp.use(bundledPluginComponent${index}, { name: ${JSON.stringify(component.namespace)} });`
		)
		.join('\n');
	return `${GENERATED_HEADER}import type { defineApp } from 'convex/server';
${imports}${imports ? '\n' : ''}
type ConvexAppDefinition = ReturnType<typeof defineApp>;

export function installBundledPluginComponents(app: ConvexAppDefinition): void {
${registrations || '\tvoid app;'}
}
`;
}

/** Kebab-case ids map injectively to Convex's alphanumeric/underscore names. */
export function convexComponentNamespace(pluginId: string): string {
	const id = parsePluginId(pluginId);
	const namespace = `plugin_${id.replaceAll('-', '_')}`;
	if (!/^[A-Za-z0-9_]+$/.test(namespace) || namespace.length > 128) {
		throw new TypeError('Plugin id cannot be represented as a Convex component namespace');
	}
	return namespace;
}
