import {
	composeBundledAgentSteps,
	orderHostedContributions,
	parsePluginPackageName,
	type BundledPlugin,
	type HostedAgentStepDefinition,
} from '@owlat/plugin-host';
import { parsePluginId } from '@owlat/plugin-kit';

const GENERATED_HEADER = `// Generated by @owlat/plugin-codegen. Do not edit by hand.\n// Run \`bun run plugins:codegen\` after changing plugins.config.ts.\n`;

export interface GeneratedPluginComposition {
	readonly convex: string;
	readonly components: string;
	readonly nuxt: string;
	readonly sendTransportCatalog: string;
	readonly sendTransportModules: string;
	readonly agentStepCatalog: string;
	readonly agentStepModules: string;
	readonly draftStrategyCatalog: string;
	readonly draftStrategyModules: string;
	readonly autonomyGateCatalog: string;
	readonly autonomyGateModules: string;
}

export function renderPluginComposition(
	plugins: readonly BundledPlugin[]
): GeneratedPluginComposition {
	const agentSteps = composeBundledAgentSteps(plugins);
	const imports = plugins
		.map((plugin, index) => {
			const packageName = JSON.stringify(parsePluginPackageName(plugin.packageName));
			return `import bundledPluginManifest${index} from ${packageName};`;
		})
		.join('\n');
	const sources = plugins
		.map((plugin, index) => {
			const packageName = JSON.stringify(parsePluginPackageName(plugin.packageName));
			return `\t{ packageName: ${packageName}, manifest: bundledPluginManifest${index} },`;
		})
		.join('\n');
	const composition = sources
		? `export const bundledPluginComposition = composeBundledPlugins([\n${sources}\n]);\n`
		: 'export const bundledPluginComposition = composeBundledPlugins([]);\n';
	const shared = `${GENERATED_HEADER}import { composeBundledPlugins } from '@owlat/plugin-host';\n${imports}${imports ? '\n' : ''}\n${composition}`;

	return Object.freeze({
		convex: shared,
		components: renderConvexComponents(plugins),
		nuxt: `${shared}\nexport default defineNuxtPlugin({\n\tname: 'owlat:bundled-plugin-composition',\n\tsetup() {\n\t\tvoid bundledPluginComposition;\n\t},\n});\n`,
		sendTransportCatalog: renderSendTransportCatalog(plugins),
		sendTransportModules: renderSendTransportModules(plugins),
		agentStepCatalog: renderAgentStepCatalog(agentSteps),
		agentStepModules: renderAgentStepModules(agentSteps),
		draftStrategyCatalog: renderDraftStrategyCatalog(plugins),
		draftStrategyModules: renderDraftStrategyModules(plugins),
		autonomyGateCatalog: renderAutonomyGateCatalog(plugins),
		autonomyGateModules: renderAutonomyGateModules(plugins),
	});
}

function autonomyGatesFor(plugins: readonly BundledPlugin[]) {
	return orderHostedContributions(
		plugins.flatMap((plugin) =>
			(plugin.manifest.contributes?.sendGates ?? []).map((gate) => ({
				pluginId: parsePluginId(plugin.manifest.id),
				contributionId: gate.id,
				value: {
					packageName: parsePluginPackageName(plugin.packageName),
					label: gate.label,
					exportPath: gate.module.exportPath,
					timeoutMs: gate.timeoutMs,
					requiredEnvVars: plugin.manifest.flag?.requiredEnvVars ?? [],
				},
			}))
		)
	).map(({ pluginId, contributionId, value }) => ({
		...value,
		pluginId,
		kind: `plugin.${pluginId}.${contributionId}`,
	}));
}

function renderAutonomyGateCatalog(plugins: readonly BundledPlugin[]): string {
	const entries = autonomyGatesFor(plugins)
		.map(
			(gate) => `\tObject.freeze({
\t\tkind: ${JSON.stringify(gate.kind)},
\t\tpluginId: ${JSON.stringify(gate.pluginId)},
\t\tlabel: ${JSON.stringify(gate.label)},
\t\ttimeoutMs: ${gate.timeoutMs},
\t\trequiredEnvVars: Object.freeze(${JSON.stringify(gate.requiredEnvVars)}),
\t\trequiredCapability: 'send:gate',
\t}),`
		)
		.join('\n');
	const catalog = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	return `${GENERATED_HEADER}export const BUNDLED_PLUGIN_AUTONOMY_GATE_CATALOG = ${catalog};\n`;
}

function renderAutonomyGateModules(plugins: readonly BundledPlugin[]): string {
	const gates = autonomyGatesFor(plugins);
	const imports = gates
		.map(
			(gate, index) =>
				`import bundledPluginAutonomyGate${index} from ${JSON.stringify(`${gate.packageName}${gate.exportPath.slice(1)}`)};`
		)
		.join('\n');
	const entries = gates
		.map(
			(gate, index) =>
				`\tObject.freeze({ kind: ${JSON.stringify(gate.kind)}, pluginId: ${JSON.stringify(gate.pluginId)}, module: bundledPluginAutonomyGate${index} satisfies PluginAutonomyGateModule }),`
		)
		.join('\n');
	const modules = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	const contractImport = gates.length
		? "import type { PluginAutonomyGateModule } from '@owlat/plugin-kit';\n"
		: '';
	return `'use node';\n\n${GENERATED_HEADER}${contractImport}${imports}${imports ? '\n\n' : ''}export const BUNDLED_PLUGIN_AUTONOMY_GATE_MODULES = ${modules};\n`;
}

function draftStrategiesFor(plugins: readonly BundledPlugin[]) {
	return plugins.flatMap((plugin) =>
		(plugin.manifest.contributes?.draftStrategies ?? []).map((strategy) => ({
			packageName: parsePluginPackageName(plugin.packageName),
			pluginId: parsePluginId(plugin.manifest.id),
			kind: `plugin.${plugin.manifest.id}.${strategy.id}`,
			label: strategy.label,
			exportPath: strategy.module.exportPath,
			timeoutMs: strategy.timeoutMs,
			requiredEnvVars: plugin.manifest.flag?.requiredEnvVars ?? [],
		}))
	);
}

function renderDraftStrategyCatalog(plugins: readonly BundledPlugin[]): string {
	const entries = draftStrategiesFor(plugins)
		.map(
			(strategy) => `\tObject.freeze({
\t\tkind: ${JSON.stringify(strategy.kind)},
\t\tpluginId: ${JSON.stringify(strategy.pluginId)},
\t\tlabel: ${JSON.stringify(strategy.label)},
\t\ttimeoutMs: ${strategy.timeoutMs},
\t\trequiredEnvVars: Object.freeze(${JSON.stringify(strategy.requiredEnvVars)}),
\t\trequiredCapability: 'draft:strategy',
\t}),`
		)
		.join('\n');
	const catalog = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	return `${GENERATED_HEADER}export const BUNDLED_PLUGIN_DRAFT_STRATEGY_CATALOG = ${catalog};\n`;
}

function renderDraftStrategyModules(plugins: readonly BundledPlugin[]): string {
	const strategies = draftStrategiesFor(plugins);
	const imports = strategies
		.map(
			(strategy, index) =>
				`import bundledPluginDraftStrategy${index} from ${JSON.stringify(`${strategy.packageName}${strategy.exportPath.slice(1)}`)};`
		)
		.join('\n');
	const entries = strategies
		.map(
			(strategy, index) =>
				`\tObject.freeze({ kind: ${JSON.stringify(strategy.kind)}, pluginId: ${JSON.stringify(strategy.pluginId)}, module: bundledPluginDraftStrategy${index} satisfies PluginDraftStrategyModule }),`
		)
		.join('\n');
	const modules = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	const contractImport = strategies.length
		? "import type { PluginDraftStrategyModule } from '@owlat/plugin-kit';\n"
		: '';
	return `'use node';\n\n${GENERATED_HEADER}${contractImport}${imports}${imports ? '\n\n' : ''}export const BUNDLED_PLUGIN_DRAFT_STRATEGY_MODULES = ${modules};\n`;
}

function renderAgentStepCatalog(steps: readonly HostedAgentStepDefinition[]): string {
	const entries = steps
		.map((step) => {
			const lifecycleEdges = step.lifecycleEdges
				.map((edge) => `Object.freeze(${JSON.stringify(edge)})`)
				.join(', ');
			return `\tObject.freeze({
\t\tkind: ${JSON.stringify(step.kind)},
\t\tpluginId: ${JSON.stringify(step.pluginId)},
\t\tafter: ${JSON.stringify(step.after)},
\t\tcontinuationStatus: ${JSON.stringify(step.continuationStatus)},
\t\tplacement: ${JSON.stringify(step.placement)},
\t\tlifecycleEdges: Object.freeze([${lifecycleEdges}]),
\t\trequiredCapability: 'agent:step',
\t}),`;
		})
		.join('\n');
	const catalog = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	return `${GENERATED_HEADER}export const BUNDLED_PLUGIN_AGENT_STEP_CATALOG = ${catalog};\n`;
}

function renderAgentStepModules(steps: readonly HostedAgentStepDefinition[]): string {
	const contractImport = steps.length
		? "import type { PluginAgentStepModule } from '@owlat/plugin-kit';\n"
		: '';
	const imports = steps
		.map(
			(step, index) =>
				`import bundledPluginAgentStep${index} from ${JSON.stringify(`${step.packageName}${step.exportPath.slice(1)}`)};`
		)
		.join('\n');
	const entries = steps
		.map(
			(step, index) =>
				`\tObject.freeze({ kind: ${JSON.stringify(step.kind)}, pluginId: ${JSON.stringify(step.pluginId)}, module: bundledPluginAgentStep${index} satisfies PluginAgentStepModule }),`
		)
		.join('\n');
	const modules = entries
		? `Object.freeze([\n${entries}\n] as const)`
		: 'Object.freeze([] as const)';
	return `'use node';\n\n${GENERATED_HEADER}${contractImport}${imports}${imports ? '\n\n' : ''}export const BUNDLED_PLUGIN_AGENT_STEP_MODULES = ${modules};\n`;
}

interface RenderedSendTransport {
	readonly packageName: string;
	readonly pluginId: string;
	readonly localId: string;
	readonly kind: string;
	readonly label: string;
	readonly exportPath: string;
	readonly retryDelays: readonly number[];
	readonly requiredEnvVars: readonly string[];
}

function sendTransportsFor(plugins: readonly BundledPlugin[]): readonly RenderedSendTransport[] {
	return plugins.flatMap((plugin) =>
		(plugin.manifest.contributes?.sendTransports ?? []).map((transport) => ({
			packageName: parsePluginPackageName(plugin.packageName),
			pluginId: parsePluginId(plugin.manifest.id),
			localId: transport.id,
			kind: `plugin.${plugin.manifest.id}.${transport.id}`,
			label: transport.label,
			exportPath: transport.module.exportPath,
			retryDelays: transport.retryDelays,
			requiredEnvVars: plugin.manifest.flag?.requiredEnvVars ?? [],
		}))
	);
}

function renderSendTransportCatalog(plugins: readonly BundledPlugin[]): string {
	const entries = sendTransportsFor(plugins)
		.map(
			(transport) => `\tObject.freeze({
\t\tkind: ${JSON.stringify(transport.kind)},
\t\tpluginId: ${JSON.stringify(transport.pluginId)},
\t\tlocalId: ${JSON.stringify(transport.localId)},
\t\tlabel: ${JSON.stringify(transport.label)},
\t\tretryDelays: Object.freeze(${JSON.stringify(transport.retryDelays)}),
\t\trequiredEnvVars: Object.freeze(${JSON.stringify(transport.requiredEnvVars)}),
\t\trequiredCapability: 'send:transport',
\t}),`
		)
		.join('\n');
	const catalog = entries ? `Object.freeze([\n${entries}\n])` : 'Object.freeze([])';
	return `${GENERATED_HEADER}export const BUNDLED_PLUGIN_SEND_TRANSPORT_CATALOG = ${catalog};\n`;
}

function renderSendTransportModules(plugins: readonly BundledPlugin[]): string {
	const transports = sendTransportsFor(plugins);
	const imports = transports
		.map(
			(transport, index) =>
				`import bundledPluginSendTransport${index} from ${JSON.stringify(`${transport.packageName}${transport.exportPath.slice(1)}`)};`
		)
		.join('\n');
	const entries = transports
		.map(
			(transport, index) =>
				`\tObject.freeze({ kind: ${JSON.stringify(transport.kind)}, pluginId: ${JSON.stringify(transport.pluginId)}, module: bundledPluginSendTransport${index} }),`
		)
		.join('\n');
	const modules = entries ? `Object.freeze([\n${entries}\n])` : 'Object.freeze([])';
	return `'use node';\n\n${GENERATED_HEADER}${imports}${imports ? '\n\n' : ''}export const BUNDLED_PLUGIN_SEND_TRANSPORT_MODULES = ${modules};\n`;
}

function renderConvexComponents(plugins: readonly BundledPlugin[]): string {
	const components = plugins.flatMap((plugin) => {
		const component = plugin.manifest.component;
		if (!component) return [];
		const packageName = parsePluginPackageName(plugin.packageName);
		const pluginId = parsePluginId(plugin.manifest.id);
		return [
			{
				moduleSpecifier: `${packageName}${component.exportPath.slice(1)}`,
				namespace: convexComponentNamespace(pluginId),
			},
		];
	});
	const imports = components
		.map(
			(component, index) =>
				`import bundledPluginComponent${index} from ${JSON.stringify(component.moduleSpecifier)};`
		)
		.join('\n');
	const registrations = components
		.map(
			(component, index) =>
				`\tapp.use(bundledPluginComponent${index}, { name: ${JSON.stringify(component.namespace)} });`
		)
		.join('\n');
	return `${GENERATED_HEADER}import type { defineApp } from 'convex/server';
${imports}${imports ? '\n' : ''}
type ConvexAppDefinition = ReturnType<typeof defineApp>;

export function installBundledPluginComponents(app: ConvexAppDefinition): void {
${registrations || '\tvoid app;'}
}
`;
}

/** Kebab-case ids map injectively to Convex's alphanumeric/underscore names. */
export function convexComponentNamespace(pluginId: string): string {
	const id = parsePluginId(pluginId);
	const namespace = `plugin_${id.replaceAll('-', '_')}`;
	if (!/^[A-Za-z0-9_]+$/.test(namespace) || namespace.length > 128) {
		throw new TypeError('Plugin id cannot be represented as a Convex component namespace');
	}
	return namespace;
}
