import type { BundledPlugin } from '@owlat/plugin-host';

const GENERATED_HEADER = `// Generated by @owlat/plugin-codegen. Do not edit by hand.\n// Run \`bun run plugins:codegen\` after changing plugins.config.ts.\n`;

export interface GeneratedPluginComposition {
	readonly convex: string;
	readonly nuxt: string;
}

export function renderPluginComposition(
	plugins: readonly BundledPlugin[]
): GeneratedPluginComposition {
	const imports = plugins
		.map((plugin, index) => `import bundledPluginManifest${index} from '${plugin.packageName}';`)
		.join('\n');
	const sources = plugins
		.map(
			(plugin, index) =>
				`\t{ packageName: '${plugin.packageName}', manifest: bundledPluginManifest${index} },`
		)
		.join('\n');
	const composition = sources
		? `export const bundledPluginComposition = composeBundledPlugins([\n${sources}\n]);\n`
		: 'export const bundledPluginComposition = composeBundledPlugins([]);\n';
	const shared = `${GENERATED_HEADER}import { composeBundledPlugins } from '@owlat/plugin-host';\n${imports}${imports ? '\n' : ''}\n${composition}`;

	return Object.freeze({
		convex: shared,
		nuxt: `${shared}\nexport default defineNuxtPlugin({\n\tname: 'owlat:bundled-plugin-composition',\n\tsetup() {\n\t\tvoid bundledPluginComposition;\n\t},\n});\n`,
	});
}
