'use node';

// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
import type { PluginAgentStepModule } from '@owlat/plugin-kit';
export const BUNDLED_PLUGIN_AGENT_STEP_MODULES = Object.freeze([] as const);
