'use node';

// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
export const BUNDLED_PLUGIN_AUTONOMY_GATE_MODULES = Object.freeze([] as const);
