// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
export const BUNDLED_PLUGIN_AUTOMATION_CONDITION_CATALOG = Object.freeze([] as const);
