// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
import type { defineApp } from 'convex/server';

type ConvexAppDefinition = ReturnType<typeof defineApp>;

export function installBundledPluginComponents(app: ConvexAppDefinition): void {
	void app;
}
