// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
import { composeBundledPlugins } from '@owlat/plugin-host';

export const bundledPluginComposition = composeBundledPlugins([]);

export default defineNuxtPlugin({
	name: 'owlat:bundled-plugin-composition',
	setup() {
		void bundledPluginComposition;
	},
});
