// Generated by @owlat/plugin-codegen. Do not edit by hand.
// Run `bun run plugins:codegen` after changing plugins.config.ts.
import type { BundledPlugin } from '@owlat/plugin-host';

// No bundled plugins: the composition is empty, so the runtime composer is not imported.
export const bundledPluginComposition: readonly BundledPlugin[] = Object.freeze([]);

export default defineNuxtPlugin({
	name: 'owlat:bundled-plugin-composition',
	setup() {
		void bundledPluginComposition;
	},
});
