// Block types
export type {
	BlockType,
	UniversalPadding,
	UniversalMargin,
	BorderStyle,
	UniversalBorder,
	TextBlockType,
	GradientBackground,
	DarkModeOverrides,
	ResponsiveVisibility,
	FullWidthOption,
	CssClassOption,
	BlockCondition,
	BlockRepeat,
	ConditionalOption,
	TextBlockContent,
	ImageBlockContent,
	ButtonBlockContent,
	DividerBlockContent,
	SpacerBlockContent,
	ColumnItem,
	ColumnRatio,
	ColumnStyle,
	ColumnsBlockContent,
	ContainerItemType,
	ContainerItemContent,
	ContainerItem,
	ContainerBlockContent,
	SocialPlatform,
	SocialLink,
	SocialBlockContent,
	HeroBlockContent,
	TableCell,
	TableColumn,
	TableResponsiveMode,
	TableBlockContent,
	RawHtmlBlockContent,
	VideoBlockContent,
	AccordionSection,
	AccordionBlockContent,
	MenuLink,
	MenuBlockContent,
	CarouselImage,
	CarouselBlockContent,
	ListBlockContent,
	ProgressBarBlockContent,
	BlockContent,
	BlockTypeContentMap,
	CommonBlockProperties,
	SavedBlockRef,
	EditorBlock,
	SavedBlock,
} from './blocks';

// Control component types (aliases for better ergonomics)
export type { Padding, Margin, Border } from './controls';

// Variable types
export type { Variable, VariableType } from './variables';

// Editor types
export type {
	EmailTheme,
	EmailBuilderMode,
	EmailBuilderConfig,
	ImageUploadResult,
	EmailBuilderHandlers,
	EmailBuilderProps,
	EmailBuilderEmits,
	PreviewDevice,
	PreviewMode,
	SlashCommand,
	SlashMenuState,
} from './editor';
