/**
 * Shared docker-compose override writer — the single renderer for
 * `docker-compose.override.yml` across the setup CLI, the web setup wizard and
 * the updater sidecar. Three independent writers previously produced three
 * drifting override shapes; every profile apply now goes through this module so
 * `.env`'s COMPOSE_PROFILES, the override file and the CLI flag mirror stay
 * convergent.
 *
 * The base compose file (the repo-root docker-compose.yml) declares `profiles:`
 * on every gated service; the override records which profiles are active
 * (`x-owlat-profiles`) plus one synthetic busybox marker service per profile.
 * Compose ignores unknown profile names, so this is forward-compatible: adding
 * a new flag with a new profile only requires updating featureFlags.ts.
 *
 * The YAML is rendered by hand rather than through a YAML library: profile
 * names are validated against SAFE_PROFILE_NAME below, every other scalar is a
 * fixed literal, and the updater bundles this module into a dependency-free
 * binary — a serializer would be its only external dependency.
 */

import { getFlagOwnedProfiles, type FeatureFlagResolutionOptions } from './featureFlags';

/**
 * Compose profile names come from the flag registry's `dockerProfiles` (plus
 * the env-driven 'mta') or from the installer (`tls`, `dashboard`); anything
 * outside this shape cannot be embedded into YAML or a COMPOSE_PROFILES line
 * verbatim, so refuse it outright.
 */
const SAFE_PROFILE_NAME = /^[a-z][a-z0-9-]*$/;

/** Render the override document for an already-derived profile list. */
export function renderComposeOverrideYaml(profiles: readonly string[]): string {
	const names = [...new Set(profiles)].sort();
	for (const profile of names) {
		if (!SAFE_PROFILE_NAME.test(profile)) {
			throw new Error(`Unsafe compose profile name: ${JSON.stringify(profile)}`);
		}
	}

	const profileList = names.length ? `\n${names.map((p) => `  - ${p}`).join('\n')}` : ' []';
	// Synthetic marker services — compose ignores keys it doesn't recognize, so
	// these just record the activation. The actual gating is COMPOSE_PROFILES in
	// .env (or `--profile` flags) passed to `docker compose up`.
	const services = names.length
		? `\n${names
				.map((p) =>
					[
						`  __${p}_marker:`,
						`    image: busybox:stable`,
						`    command: "true"`,
						`    profiles:`,
						`      - ${p}`,
						`    restart: "no"`,
					].join('\n')
				)
				.join('\n')}`
		: ' {}';

	return (
		`# Generated by Owlat. DO NOT EDIT MANUALLY.\n` +
		`# Active profiles: ${names.join(', ') || '(none)'}\n` +
		`\n` +
		`x-owlat-profiles:${profileList}\n` +
		`x-owlat-generated-at: "${new Date().toISOString()}"\n` +
		`services:${services}\n`
	);
}

/**
 * The COMPOSE_PROFILES a flag apply should leave behind: the profiles the flags
 * derive, plus every applied profile the flag registry does not own.
 *
 * A flag apply knows what the FLAGS want. It does not know what the INSTALL
 * chose — `tls` (the Caddy edge that terminates HTTPS) and `dashboard` (the
 * Convex dashboard) are written by the installer and can never be re-derived
 * from a flag state. Writing the derived set as the whole line dropped them,
 * and the `docker compose up -d --remove-orphans` that follows then removed the
 * containers behind them: one click on "Apply & restart" took the reverse proxy
 * down and the instance with it.
 *
 * Union, not replacement, over the install-owned half; straight replacement
 * over the flag-owned half, so turning a flag OFF still stops its service.
 */
export function mergeComposeProfiles(
	applied: readonly string[],
	derived: readonly string[],
	opts: FeatureFlagResolutionOptions = {}
): string[] {
	const flagOwned = getFlagOwnedProfiles(opts);
	const preserved = applied.filter(
		(profile) => !flagOwned.has(profile) && SAFE_PROFILE_NAME.test(profile)
	);
	return [...new Set([...derived, ...preserved])].sort();
}

/**
 * Read the delivery provider (EMAIL_PROVIDER) out of a `.env` file's text.
 * The built-in MTA's `mta` profile activates when MTA is the delivery provider
 * (env-driven, not a flag) — post-setup flag toggles read the co-located .env
 * through this parser so an MTA deployment keeps its MTA running.
 */
export function parseDeliveryProviderFromEnv(envText: string): string | undefined {
	const match = envText.match(/^\s*EMAIL_PROVIDER\s*=\s*(.+?)\s*$/m);
	return match?.[1]?.replace(/^["']|["']$/g, '');
}

/**
 * Read the APPLIED compose profiles (COMPOSE_PROFILES) out of a `.env` file's
 * text — the inverse of what the writer above converges. The drift probe
 * compares this against the profiles the current flag state derives, so a
 * reload can rebuild the "services out of sync" banner from the host's real
 * state instead of per-tab memory.
 *
 * Names outside SAFE_PROFILE_NAME are dropped: the writer can only ever emit
 * that shape, so anything else is a hand-edit this module has no mapping for
 * (and must never be echoed back into a COMPOSE_PROFILES line or YAML).
 */
export function parseComposeProfilesFromEnv(envText: string): string[] {
	const match = envText.match(/^\s*COMPOSE_PROFILES\s*=\s*(.*?)\s*$/m);
	return parseComposeProfileList(match?.[1] ?? '');
}

/**
 * The same read, for a caller holding the COMPOSE_PROFILES VALUE rather than
 * the `.env` text around it (the setup wizard reads `.env` into a map before it
 * gets here). Same filter, so both readers agree on what a profile name is.
 */
export function parseComposeProfileList(value: string): string[] {
	const names = value
		.replace(/^["']|["']$/g, '')
		.split(',')
		.map((name) => name.trim())
		.filter((name) => SAFE_PROFILE_NAME.test(name));
	return [...new Set(names)].sort();
}
