/**
 * Setup-time `.env` read / parse / merge / write helpers.
 *
 * NODE-ONLY: uses `node:fs`. Shared by the `owlat-setup` CLI (`apps/setup-cli`)
 * and the web setup endpoint (`apps/web/server/api/setup/apply.post.ts`) so the
 * two can never drift on how `.env` files are parsed or serialized. Exposed via
 * the `@owlat/shared/setupEnv` subpath ONLY — it must never be re-exported from
 * the `.` barrel, which has to stay browser-safe.
 *
 * Tolerates BASH-style files with comments and blank lines. On write, values
 * containing whitespace or shell metacharacters are double-quoted; insertion
 * order is preserved.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

export type EnvMap = Record<string, string>;

export async function readEnvFile(path: string): Promise<EnvMap> {
	if (!existsSync(path)) return {};
	const raw = await readFile(path, 'utf-8');
	const map: EnvMap = {};
	for (const line of raw.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		let value = trimmed.slice(eq + 1).trim();
		if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
			value = value.slice(1, -1);
		}
		map[key] = value;
	}
	return map;
}

export async function writeEnvFile(path: string, map: EnvMap): Promise<void> {
	const lines: string[] = [
		'# Generated by Owlat setup. Re-run setup to update.',
		`# Last updated: ${new Date().toISOString()}`,
		'',
	];
	for (const [key, value] of Object.entries(map)) {
		// Quote values containing whitespace, =, or shell metacharacters.
		const needsQuotes = /[\s="'`$\\]/.test(value);
		lines.push(needsQuotes ? `${key}="${value.replace(/"/g, '\\"')}"` : `${key}=${value}`);
	}
	await writeFile(path, lines.join('\n') + '\n', { mode: 0o600 });
}

/**
 * Merge new values into an existing env map, preserving prior keys not in the
 * patch. Use this to incrementally apply wizard answers without clobbering the
 * operator's manual edits.
 */
export function mergeEnv(existing: EnvMap, patch: EnvMap): EnvMap {
	return { ...existing, ...patch };
}
