/**
 * Curated `:shortcode:` emoji set for the Postbox composer picker.
 *
 * Deliberately SMALL and static — a hand-picked list of the most commonly used
 * emoji (a few hundred), NOT a full Unicode database. No external dependency,
 * no skin-tone variants, no recents. The character is inserted as plain text so
 * it renders universally in email; the shortcode/name only feed the fuzzy
 * filter and are never sent.
 *
 * Entries are `[shortcode, name, char]` tuples (compact so the file stays well
 * under the file-size ratchet). `shortcode` is the `:foo:` token without colons;
 * `name` is extra human words the fuzzy filter also matches on.
 */

export interface PostboxEmoji {
	/** The `:shortcode:` token, without the surrounding colons. */
	shortcode: string;
	/** Extra descriptive words the fuzzy filter also matches against. */
	name: string;
	/** The literal emoji character inserted into the draft (plain text). */
	char: string;
}

type EmojiTuple = readonly [shortcode: string, name: string, char: string];

// prettier-ignore
const RAW: readonly EmojiTuple[] = [
	['smile', 'smiling face happy', '😄'],
	['smiley', 'smiling face open mouth', '😃'],
	['grin', 'grinning face', '😁'],
	['grinning', 'grinning face happy', '😀'],
	['laughing', 'laugh satisfied haha', '😆'],
	['sweat_smile', 'smile sweat nervous', '😅'],
	['joy', 'tears of joy laughing crying', '😂'],
	['rofl', 'rolling on floor laughing', '🤣'],
	['relaxed', 'relaxed smile', '☺️'],
	['blush', 'smiling blushing shy', '😊'],
	['innocent', 'angel halo innocent', '😇'],
	['slight_smile', 'slightly smiling', '🙂'],
	['upside_down', 'upside down silly', '🙃'],
	['wink', 'winking face', '😉'],
	['relieved', 'relieved calm', '😌'],
	['heart_eyes', 'love heart eyes', '😍'],
	['kissing_heart', 'blowing kiss', '😘'],
	['kissing', 'kiss face', '😗'],
	['yum', 'savoring delicious tongue', '😋'],
	['stuck_out_tongue', 'tongue out playful', '😛'],
	['stuck_out_tongue_winking_eye', 'tongue wink', '😜'],
	['zany', 'zany goofy crazy', '🤪'],
	['sunglasses', 'cool sunglasses', '😎'],
	['nerd', 'nerd glasses', '🤓'],
	['star_struck', 'star struck amazed', '🤩'],
	['thinking', 'thinking hmm', '🤔'],
	['face_with_raised_eyebrow', 'skeptic raised eyebrow', '🤨'],
	['neutral_face', 'neutral meh', '😐'],
	['expressionless', 'expressionless blank', '😑'],
	['no_mouth', 'no mouth speechless', '😶'],
	['smirk', 'smirk sly', '😏'],
	['unamused', 'unamused annoyed', '😒'],
	['roll_eyes', 'rolling eyes', '🙄'],
	['grimacing', 'grimace awkward', '😬'],
	['lying', 'lying pinocchio', '🤥'],
	['relieved_pensive', 'pensive sad', '😔'],
	['sleepy', 'sleepy tired', '😪'],
	['drooling', 'drooling', '🤤'],
	['sleeping', 'sleeping zzz', '😴'],
	['mask', 'medical mask sick', '😷'],
	['thermometer_face', 'sick fever', '🤒'],
	['nauseated', 'nauseated sick', '🤢'],
	['vomiting', 'vomiting sick', '🤮'],
	['sneezing', 'sneezing sick', '🤧'],
	['hot_face', 'hot overheated', '🥵'],
	['cold_face', 'cold freezing', '🥶'],
	['woozy', 'woozy dizzy drunk', '🥴'],
	['dizzy_face', 'dizzy knocked out', '😵'],
	['exploding_head', 'mind blown', '🤯'],
	['cowboy', 'cowboy hat', '🤠'],
	['partying', 'party celebrate', '🥳'],
	['smiling_imp', 'devil imp', '😈'],
	['imp', 'angry devil', '👿'],
	['clown', 'clown', '🤡'],
	['ghost', 'ghost boo', '👻'],
	['skull', 'skull dead', '💀'],
	['alien', 'alien ufo', '👽'],
	['robot', 'robot bot', '🤖'],
	['poop', 'pile of poo', '💩'],
	['smiley_cat', 'happy cat', '😺'],
	['heart_eyes_cat', 'love cat', '😻'],
	['worried', 'worried concerned', '😟'],
	['slight_frown', 'slightly frowning', '🙁'],
	['frowning', 'frowning sad', '😦'],
	['anguished', 'anguished', '😧'],
	['open_mouth', 'surprised open mouth', '😮'],
	['hushed', 'hushed surprised', '😯'],
	['astonished', 'astonished shocked', '😲'],
	['flushed', 'flushed embarrassed', '😳'],
	['pleading', 'pleading puppy eyes', '🥺'],
	['anguished', 'anguished open mouth', '😧'],
	['cry', 'crying sad tear', '😢'],
	['sob', 'sobbing crying loud', '😭'],
	['scream', 'scream fear', '😱'],
	['confounded', 'confounded', '😖'],
	['persevere', 'persevering struggle', '😣'],
	['disappointed', 'disappointed sad', '😞'],
	['sweat', 'sweat downcast', '😓'],
	['weary', 'weary tired', '😩'],
	['tired_face', 'tired exhausted', '😫'],
	['yawning', 'yawn bored', '🥱'],
	['triumph', 'triumph frustrated', '😤'],
	['rage', 'rage angry mad', '😡'],
	['angry', 'angry mad', '😠'],
	['cursing', 'swearing symbols', '🤬'],
	['smiling_face_with_tear', 'happy tear grateful', '🥲'],
	['hugging', 'hugging hug', '🤗'],
	['shushing', 'shush quiet', '🤫'],
	['hand_over_mouth', 'giggle oops', '🤭'],
	['zipper_mouth', 'zipped lips secret', '🤐'],
	['money_mouth', 'money rich', '🤑'],
	['salute', 'saluting face', '🫡'],
	['melting', 'melting hot', '🫠'],
	['dotted_line_face', 'invisible disappear', '🫥'],
	['wave', 'waving hand hello bye', '👋'],
	['raised_back_of_hand', 'raised hand', '🤚'],
	['raised_hand', 'stop raised hand', '✋'],
	['vulcan', 'vulcan salute', '🖖'],
	['ok_hand', 'ok hand perfect', '👌'],
	['pinched_fingers', 'pinched fingers', '🤌'],
	['pinching', 'pinching small', '🤏'],
	['victory', 'peace victory', '✌️'],
	['crossed_fingers', 'fingers crossed luck', '🤞'],
	['love_you_gesture', 'love you gesture', '🤟'],
	['metal', 'rock on horns', '🤘'],
	['call_me', 'call me hand', '🤙'],
	['point_left', 'pointing left', '👈'],
	['point_right', 'pointing right', '👉'],
	['point_up', 'pointing up', '👆'],
	['point_down', 'pointing down', '👇'],
	['thumbsup', 'thumbs up like yes approve', '👍'],
	['thumbsdown', 'thumbs down dislike no', '👎'],
	['fist', 'raised fist', '✊'],
	['punch', 'fist bump punch', '👊'],
	['clap', 'clapping applause', '👏'],
	['raised_hands', 'raised hands celebrate hooray', '🙌'],
	['open_hands', 'open hands', '👐'],
	['palms_up', 'palms up together', '🤲'],
	['handshake', 'handshake deal agreement', '🤝'],
	['pray', 'prayer thanks please', '🙏'],
	['writing_hand', 'writing pen', '✍️'],
	['nail_care', 'nail polish manicure', '💅'],
	['muscle', 'flexed biceps strong', '💪'],
	['point_up_2', 'index pointing up', '☝️'],
	['heart', 'red heart love', '❤️'],
	['orange_heart', 'orange heart', '🧡'],
	['yellow_heart', 'yellow heart', '💛'],
	['green_heart', 'green heart', '💚'],
	['blue_heart', 'blue heart', '💙'],
	['purple_heart', 'purple heart', '💜'],
	['black_heart', 'black heart', '🖤'],
	['white_heart', 'white heart', '🤍'],
	['brown_heart', 'brown heart', '🤎'],
	['broken_heart', 'broken heart sad', '💔'],
	['two_hearts', 'two hearts love', '💕'],
	['sparkling_heart', 'sparkling heart', '💖'],
	['heartpulse', 'growing heart', '💗'],
	['cupid', 'heart arrow cupid', '💘'],
	['gift_heart', 'heart ribbon', '💝'],
	['revolving_hearts', 'revolving hearts', '💞'],
	['heavy_heart_exclamation', 'heart exclamation', '❣️'],
	['love_letter', 'love letter', '💌'],
	['kiss_mark', 'kiss lips', '💋'],
	['hundred', '100 perfect score', '💯'],
	['anger', 'anger symbol', '💢'],
	['boom', 'collision explosion', '💥'],
	['dizzy', 'dizzy stars', '💫'],
	['sweat_drops', 'sweat drops', '💦'],
	['dash', 'dashing away wind', '💨'],
	['sparkles', 'sparkles shiny', '✨'],
	['star', 'star', '⭐'],
	['star2', 'glowing star', '🌟'],
	['zap', 'lightning bolt zap', '⚡'],
	['fire', 'fire flame lit hot', '🔥'],
	['rainbow', 'rainbow', '🌈'],
	['sunny', 'sun sunny', '☀️'],
	['partly_sunny', 'partly cloudy', '⛅'],
	['cloud', 'cloud', '☁️'],
	['snowflake', 'snowflake snow cold', '❄️'],
	['umbrella', 'umbrella rain', '☔'],
	['droplet', 'droplet water', '💧'],
	['ocean', 'ocean wave water', '🌊'],
	['moon', 'crescent moon night', '🌙'],
	['tada', 'party popper celebrate congrats', '🎉'],
	['confetti_ball', 'confetti ball', '🎊'],
	['balloon', 'balloon party', '🎈'],
	['gift', 'gift present', '🎁'],
	['trophy', 'trophy winner award', '🏆'],
	['medal', 'sports medal', '🏅'],
	['first_place', 'first place gold', '🥇'],
	['crown', 'crown king queen', '👑'],
	['gem', 'gem diamond', '💎'],
	['rocket', 'rocket launch fast', '🚀'],
	['airplane', 'airplane flight travel', '✈️'],
	['car', 'car automobile', '🚗'],
	['checkered_flag', 'race finish flag', '🏁'],
	['bulb', 'light bulb idea', '💡'],
	['moneybag', 'money bag', '💰'],
	['dollar', 'dollar banknote money', '💵'],
	['credit_card', 'credit card payment', '💳'],
	['chart', 'chart increasing money', '💹'],
	['chart_up', 'chart increasing trend', '📈'],
	['chart_down', 'chart decreasing', '📉'],
	['bar_chart', 'bar chart stats', '📊'],
	['clipboard', 'clipboard', '📋'],
	['pushpin', 'pushpin pin', '📌'],
	['paperclip', 'paperclip attach', '📎'],
	['pencil', 'pencil write note', '📝'],
	['pen', 'fountain pen', '🖊️'],
	['book', 'open book read', '📖'],
	['books', 'stack of books', '📚'],
	['calendar', 'calendar date', '📅'],
	['date', 'calendar spiral', '📆'],
	['email', 'envelope email mail', '✉️'],
	['inbox', 'inbox tray', '📥'],
	['outbox', 'outbox tray sent', '📤'],
	['mailbox', 'mailbox', '📬'],
	['phone', 'telephone call', '📞'],
	['mobile', 'mobile phone', '📱'],
	['computer', 'laptop computer', '💻'],
	['desktop', 'desktop computer', '🖥️'],
	['keyboard', 'keyboard', '⌨️'],
	['printer', 'printer', '🖨️'],
	['floppy_disk', 'save floppy disk', '💾'],
	['magnifying_glass', 'search magnifying glass', '🔍'],
	['lock', 'locked padlock secure', '🔒'],
	['unlock', 'unlocked open', '🔓'],
	['key', 'key', '🔑'],
	['link', 'link chain', '🔗'],
	['bell', 'bell notification', '🔔'],
	['mute', 'bell muted silent', '🔕'],
	['loudspeaker', 'loudspeaker announce', '📢'],
	['mega', 'megaphone shout', '📣'],
	['hourglass', 'hourglass time', '⌛'],
	['watch', 'watch time', '⌚'],
	['alarm_clock', 'alarm clock', '⏰'],
	['coffee', 'coffee tea hot drink', '☕'],
	['tea', 'teacup', '🍵'],
	['beer', 'beer mug', '🍺'],
	['clink', 'cheers clinking beers', '🍻'],
	['wine', 'wine glass', '🍷'],
	['champagne', 'champagne celebrate', '🍾'],
	['cake', 'birthday cake', '🎂'],
	['pizza', 'pizza', '🍕'],
	['hamburger', 'hamburger burger', '🍔'],
	['fries', 'french fries', '🍟'],
	['taco', 'taco', '🌮'],
	['apple', 'red apple fruit', '🍎'],
	['banana', 'banana', '🍌'],
	['strawberry', 'strawberry', '🍓'],
	['watermelon', 'watermelon', '🍉'],
	['cookie', 'cookie', '🍪'],
	['doughnut', 'donut doughnut', '🍩'],
	['dog', 'dog puppy', '🐶'],
	['cat', 'cat kitten', '🐱'],
	['mouse', 'mouse', '🐭'],
	['fox', 'fox', '🦊'],
	['bear', 'bear', '🐻'],
	['panda', 'panda', '🐼'],
	['lion', 'lion', '🦁'],
	['tiger', 'tiger', '🐯'],
	['unicorn', 'unicorn', '🦄'],
	['penguin', 'penguin', '🐧'],
	['bird', 'bird', '🐦'],
	['bug', 'bug insect', '🐛'],
	['butterfly', 'butterfly', '🦋'],
	['bee', 'honeybee bee', '🐝'],
	['turtle', 'turtle', '🐢'],
	['fish', 'fish', '🐟'],
	['whale', 'whale', '🐳'],
	['dolphin', 'dolphin', '🐬'],
	['flower', 'blossom flower', '🌸'],
	['rose', 'rose', '🌹'],
	['sunflower', 'sunflower', '🌻'],
	['tulip', 'tulip', '🌷'],
	['four_leaf_clover', 'four leaf clover luck', '🍀'],
	['tree', 'evergreen tree', '🌲'],
	['palm_tree', 'palm tree', '🌴'],
	['cactus', 'cactus', '🌵'],
	['leaves', 'leaves nature', '🍃'],
	['maple_leaf', 'maple leaf autumn', '🍁'],
	['mushroom', 'mushroom', '🍄'],
	['earth', 'earth globe world', '🌍'],
	['check', 'check mark done yes', '✅'],
	['ballot_check', 'check box ticked', '☑️'],
	['heavy_check', 'heavy check mark', '✔️'],
	['x', 'cross mark no wrong', '❌'],
	['negative_squared_cross', 'no cross square', '❎'],
	['warning', 'warning caution', '⚠️'],
	['no_entry', 'no entry forbidden', '⛔'],
	['question', 'question mark', '❓'],
	['exclamation', 'exclamation mark', '❗'],
	['bangbang', 'double exclamation', '‼️'],
	['information', 'information info', 'ℹ️'],
	['recycle', 'recycle', '♻️'],
	['heavy_plus', 'plus add', '➕'],
	['heavy_minus', 'minus subtract', '➖'],
	['heavy_multiplication', 'multiply times', '✖️'],
	['heavy_division', 'divide', '➗'],
	['infinity', 'infinity', '♾️'],
	['arrow_right', 'right arrow', '➡️'],
	['arrow_left', 'left arrow', '⬅️'],
	['arrow_up', 'up arrow', '⬆️'],
	['arrow_down', 'down arrow', '⬇️'],
	['arrows_counterclockwise', 'refresh sync counterclockwise', '🔄'],
	['back', 'back arrow', '🔙'],
	['soon', 'soon arrow', '🔜'],
	['ok', 'ok button', '🆗'],
	['new', 'new button', '🆕'],
	['top', 'top arrow', '🔝'],
	['green_circle', 'green circle', '🟢'],
	['red_circle', 'red circle', '🔴'],
	['yellow_circle', 'yellow circle', '🟡'],
	['blue_circle', 'blue circle', '🔵'],
	['white_circle', 'white circle', '⚪'],
	['black_circle', 'black circle', '⚫'],
	['eyes', 'eyes looking', '👀'],
	['eye', 'eye', '👁️'],
	['brain', 'brain smart', '🧠'],
	['footprints', 'footprints', '👣'],
	['speech_balloon', 'speech bubble comment', '💬'],
	['thought_balloon', 'thought bubble', '💭'],
	['zzz', 'sleeping zzz', '💤'],
	['hole', 'hole', '🕳️'],
];

/** The curated Postbox emoji list (frozen, immutable). */
export const POSTBOX_EMOJI: readonly PostboxEmoji[] = Object.freeze(
	RAW.map(([shortcode, name, char]) => Object.freeze({ shortcode, name, char })),
);
