/**
 * DNS zone generation: the golden zone text, and the rules the compatibility
 * views have to keep (spec 08 §8.1).
 *
 * The golden is pinned line by line rather than read from a file, so a change
 * to the published zone is a reviewable diff in the test that claims it.
 */

import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { generateEd25519KeyPair, parseDnsTierAnswer } from '@owlat/ostr-core';
import { MaterializedScoreIndex } from '../scoreIndex.js';
import { renderZone, type ZoneRow } from '../zone.js';
import { FakeLog } from './fakeLog.js';
import { AS_OF, corpus, newcomerEntries } from './fixtures.js';

const ZONE = { origin: 'ostr.example', refBaseUrl: 'https://ostr.example/s' };

const GOLDEN = [
	'; OSTR query zone for ostr.example, generated by the reference aggregator.',
	'; Derived from the transparency log; never hand-edited (spec 08 §8.1).',
	';',
	'; A subject the policy admitted no evidence for has no name here and',
	'; answers NXDOMAIN — never tier=unknown (spec 08 §8.1 requires one of',
	'; the two, documented; this is the one).',
	';',
	'; DNSSEC: this is the unsigned zone. It MUST be served signed — online',
	'; signing with NSEC3 or compact denial of existence, since it churns',
	"; hourly — but that is the DNS server's job, not the aggregator's.",
	'$ORIGIN ostr.example.',
	'$TTL 3600',
	'@\t3600\tIN\tSOA\tns1.ostr.example. hostmaster.ostr.example. 1787184000 3600 900 1209600 3600',
	'@\t3600\tIN\tNS\tns1.ostr.example.',
	'@\t3600\tIN\tNS\tns2.ostr.example.',
	'',
	'; tier answers under q.ostr.example',
	'7.100.51.198.ip.q.ostr.example.\t3600\tIN\tTXT\t"v=1; tier=flagged; score=0; policy=ostr-policy-v1; asof=2026-08-20T00:00:00Z; ref=https://ostr.example/s/198.51.100.7"',
	'abusive.example.q.ostr.example.\t3600\tIN\tTXT\t"v=1; tier=flagged; score=0; policy=ostr-policy-v1; asof=2026-08-20T00:00:00Z; ref=https://ostr.example/s/abusive.example"',
	'tenant.example.q.ostr.example.\t3600\tIN\tTXT\t"v=1; tier=establishing; score=55; policy=ostr-policy-v1; asof=2026-08-20T00:00:00Z; ref=https://ostr.example/s/tenant.example"',
	'veteran.example.q.ostr.example.\t3600\tIN\tTXT\t"v=1; tier=trusted; score=98; policy=ostr-policy-v1; asof=2026-08-20T00:00:00Z; ref=https://ostr.example/s/veteran.example"',
	'',
	'; bl.ostr.example compatibility view: flagged subjects only',
	'7.100.51.198.bl.ostr.example.\t3600\tIN\tA\t127.0.0.2',
	'abusive.example.bl.ostr.example.\t3600\tIN\tA\t127.0.0.2',
	'',
	'; wl.ostr.example compatibility view: trusted subjects only',
	'veteran.example.wl.ostr.example.\t3600\tIN\tA\t127.0.0.2',
	'',
].join('\n');

let dir: string;
let log: FakeLog;
let index: MaterializedScoreIndex;

beforeEach(async () => {
	dir = mkdtempSync(join(tmpdir(), 'ostr-zone-'));
	log = new FakeLog(generateEd25519KeyPair().privateKey);
	log.append(corpus());
	await log.publishHead(AS_OF);
	index = new MaterializedScoreIndex({
		dbPath: join(dir, 'aggregator.db'),
		log,
		aggregatorPrivateKeyBase64: generateEd25519KeyPair().privateKey,
		zone: ZONE,
	});
	await index.refresh(AS_OF);
});

afterEach(() => {
	index.close();
	rmSync(dir, { recursive: true, force: true });
});

function recordsUnder(zone: string, view: string): string[] {
	const suffix = `.${view}.${ZONE.origin}.`;
	return zone
		.split('\n')
		.filter((line) => line.includes(`${suffix}\t`))
		.map((line) => (line.split('\t')[0] ?? '').slice(0, -suffix.length));
}

describe('dnsZone', () => {
	it('matches the pinned zone text', async () => {
		expect(await index.dnsZone()).toBe(GOLDEN);
	});

	it('is a pure function of the materialized set', async () => {
		const once = await index.dnsZone();
		await index.refresh(AS_OF);
		expect(await index.dnsZone()).toBe(once);
	});

	it('renders once per refresh, and again as soon as one lands', async () => {
		// Rebuilding the whole zone per request is the most expensive answer this
		// node serves, and between two refreshes it can only produce the same
		// bytes. Corrupting the scored set under the held text is how a second
		// read of it becomes visible: it would throw instead of answering.
		const once = await index.dnsZone();
		const db = new Database(join(dir, 'aggregator.db'));
		db.prepare('UPDATE scores SET explanation = \'[{"signal": 7}]\'').run();
		db.close();

		expect(await index.dnsZone()).toBe(once);

		// A refresh replaces the scored set, and the held text with it.
		log.append(newcomerEntries());
		await log.publishHead(AS_OF);
		await index.refresh(AS_OF);

		expect(await index.dnsZone()).toContain('newcomer.example.q.ostr.example.');
	});

	it('serves TXT answers the reference parser accepts', async () => {
		const zone = await index.dnsZone();
		const answers = zone
			.split('\n')
			.filter((line) => line.includes('\tTXT\t'))
			.map((line) => (line.split('\tTXT\t')[1] ?? '').slice(1, -1));

		expect(answers).toHaveLength(4);
		for (const answer of answers) {
			const parsed = parseDnsTierAnswer(answer);
			expect(parsed.ok).toBe(true);
		}
	});

	it('lists exactly the flagged subjects in bl. and exactly the trusted ones in wl.', async () => {
		const zone = await index.dnsZone();

		expect(recordsUnder(zone, 'bl').sort()).toEqual(['7.100.51.198', 'abusive.example']);
		expect(recordsUnder(zone, 'wl')).toEqual(['veteran.example']);
	});

	it('answers the compat views with the DNSBL 127.0.0.x convention', async () => {
		const zone = await index.dnsZone();
		const listings = zone.split('\n').filter((line) => line.includes('\tA\t'));

		expect(listings).toHaveLength(3);
		for (const listing of listings) expect(listing.endsWith('\tIN\tA\t127.0.0.2')).toBe(true);
	});
});

describe('renderZone', () => {
	const row = (over: Partial<ZoneRow>): ZoneRow => ({
		subject: { domain: 'example.test' },
		tier: 'unknown',
		score: 40,
		policy: 'ostr-policy-v1',
		...over,
	});

	it('reverses IPv6 subjects by nibble', () => {
		const zone = renderZone(
			[row({ subject: { ip: '2001:db8::1' }, tier: 'flagged', score: 3 })],
			ZONE,
			AS_OF
		);

		const expected =
			'1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip.q.ostr.example.';
		expect(zone).toContain(`${expected}\t3600\tIN\tTXT\t`);
		expect(zone).toContain(
			'1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.bl.ostr.example.\t3600\tIN\tA\t127.0.0.2'
		);
	});

	it('publishes no name for an (ip, domain) pair', () => {
		const zone = renderZone(
			[row({ subject: { domain: 'tenant.test', ip: '203.0.113.9' }, tier: 'flagged', score: 2 })],
			ZONE,
			AS_OF
		);

		expect(zone).not.toContain('tenant.test');
		expect(zone).not.toContain('9.113.0.203');
	});

	it('emits a header even for an empty scored set', () => {
		const zone = renderZone([], ZONE, '1970-01-01T00:00:00Z');

		expect(zone).toContain('$ORIGIN ostr.example.');
		expect(zone).toContain('hostmaster.ostr.example. 0 3600 900 1209600 3600');
		expect(zone).not.toContain('IN\tTXT');
	});

	it('accepts a trailing-dot origin and normalizes it', () => {
		const zone = renderZone([row({})], { ...ZONE, origin: 'OSTR.Example.' }, AS_OF);

		expect(zone).toContain('example.test.q.ostr.example.\t3600\tIN\tTXT\t');
		expect(zone).not.toContain('ostr.example..');
	});

	it('splits an over-long answer into character-strings of one TXT record', () => {
		const long = `https://ostr.example/${'s'.repeat(300)}`;
		const zone = renderZone([row({})], { ...ZONE, refBaseUrl: long }, AS_OF);
		const line = zone.split('\n').find((candidate) => candidate.includes('\tTXT\t')) ?? '';
		const rdata = line.split('\tTXT\t')[1] ?? '';

		expect(rdata.split('" "')).toHaveLength(2);
		for (const chunk of rdata.split('" "')) {
			expect(chunk.replace(/^"|"$/g, '').length).toBeLessThanOrEqual(255);
		}
	});

	it('splits on UTF-8 bytes, not on code units', () => {
		// A character-string is capped in bytes. Counting characters would emit
		// chunks a zone loader rejects the moment the operator's base URL is not
		// pure ASCII.
		const long = `https://ostr.example/${'ü'.repeat(200)}`;
		const zone = renderZone([row({})], { ...ZONE, refBaseUrl: long }, AS_OF);
		const rdata = (zone.split('\n').find((line) => line.includes('\tTXT\t')) ?? '').split(
			'\tTXT\t'
		)[1];
		const chunks = (rdata ?? '').split('" "');
		const encoder = new TextEncoder();

		expect(chunks.length).toBeGreaterThan(1);
		for (const chunk of chunks) {
			expect(encoder.encode(chunk.replace(/^"|"$/g, '')).length).toBeLessThanOrEqual(255);
		}
	});

	it('refuses a row whose label could inject records, and says so', () => {
		const injected = 'evil.test\n@\t3600\tIN\tNS\tns1.attacker.test';
		const skipped: string[] = [];

		const zone = renderZone(
			[row({ subject: { domain: injected } }), row({ subject: { ip: '10.0.0.1/8' } })],
			ZONE,
			AS_OF,
			(_, reason) => skipped.push(reason)
		);

		expect(zone).not.toContain('attacker.test');
		expect(zone.split('\n').filter((line) => line.includes('\tNS\t'))).toHaveLength(2);
		expect(skipped).toEqual([
			'domain is not a renderable FQDN',
			'ip is not a renderable address literal',
		]);
	});

	it('rejects an origin or a nameserver it cannot render', () => {
		expect(() => renderZone([], { ...ZONE, origin: 'ostr.example\nevil' }, AS_OF)).toThrow(
			/origin is not a domain name/
		);
		expect(() =>
			renderZone([], { ...ZONE, nameservers: ['ns1.dns.test', 'not a name'] }, AS_OF)
		).toThrow(/nameservers\[1\]/);
		expect(() => renderZone([], { ...ZONE, nameservers: [] }, AS_OF)).toThrow(/at least one/);
		expect(() => renderZone([], { ...ZONE, refBaseUrl: 'javascript:alert(1)' }, AS_OF)).toThrow(
			/refBaseUrl must be http/
		);
		expect(() => renderZone([], { ...ZONE, ttlSeconds: 0 }, AS_OF)).toThrow(/ttlSeconds/);
	});

	it('publishes the nameservers, primary and hostmaster an operator configures', () => {
		const zone = renderZone(
			[],
			{
				...ZONE,
				nameservers: ['a.ns.vendor.test', 'b.ns.vendor.test', 'c.ns.vendor.test'],
				primaryNameserver: 'hidden.primary.test',
				hostmaster: 'dns-ops.example',
				ttlSeconds: 900,
				soa: { retry: 300 },
			},
			AS_OF
		);

		expect(zone).toContain(
			'@\t900\tIN\tSOA\thidden.primary.test. dns-ops.example. 1787184000 3600 300 1209600 3600'
		);
		expect(zone.split('\n').filter((line) => line.includes('\tNS\t'))).toEqual([
			'@\t900\tIN\tNS\ta.ns.vendor.test.',
			'@\t900\tIN\tNS\tb.ns.vendor.test.',
			'@\t900\tIN\tNS\tc.ns.vendor.test.',
		]);
	});

	it('refuses to publish a zone with an unusable as-of instant', () => {
		// Serial 0 would look older than every zone published before it.
		expect(() => renderZone([row({})], ZONE, 'not-an-instant')).toThrow(/not RFC 3339/);
		expect(() => renderZone([row({})], ZONE, '2026-08-20T00:00:00+02:00')).toThrow(/not RFC 3339/);
	});

	it('reverses an IPv4 address the way the TXT zone does', () => {
		// Pins the reversal the bl./wl. views borrow from core, so a change to
		// the query-name shape fails here rather than silently listing wrong
		// names in the compat views.
		const zone = renderZone(
			[row({ subject: { ip: '192.0.2.7' }, tier: 'flagged', score: 1 })],
			ZONE,
			AS_OF
		);

		expect(zone).toContain('7.2.0.192.bl.ostr.example.\t3600\tIN\tA\t127.0.0.2');
		expect(zone).toContain('7.2.0.192.ip.q.ostr.example.\t3600\tIN\tTXT\t');
	});

	it('documents the NXDOMAIN choice spec 08 §8.1 requires an aggregator to state', () => {
		const zone = renderZone([], ZONE, AS_OF);

		expect(zone).toContain('answers NXDOMAIN');
	});
});
